import {internal_enterBomOutput,internal_leaveBomOutput, internal_enterBomPartMasterDataElements,internal_leaveBomPartMasterDataElements, internal_enterBomPartMasterDataTouches,internal_leaveBomPartMasterDataTouches, internal_enterFunction,internal_leaveFunction, internal_enterModuleManufacturerDataCompletion,internal_leaveModuleManufacturerDataCompletion, internal_enterModuleAfterDataCompletion,internal_leaveModuleAfterDataCompletion, internal_enterModuleCreateBuildPlan,internal_leaveModuleCreateBuildPlan, internal_enterCollectParts,internal_leaveCollectParts, internal_enterCheckPartAttributes,internal_leaveCheckPartAttributes,internal_enterValidateVariant,internal_leaveValidateVariant,logFatal,logError,logWarning,logInfo,logDebug,getLogMessages, clearLogMessages, internal_enterBomOrderOutput, internal_leaveBomOrderOutput, getAttrChangeLogs, internal_enterLoadJson, internal_leaveLoadJson, internal_enterDataCompletionAssignDerivedData, internal_leaveDataCompletionAssignDerivedData, internal_enterDataCompletionSetDefault, internal_leaveDataCompletionSetDefault, logAttrChange, internal_enterDataCompletionSetGlobalVars, internal_leaveDataCompletionSetGlobalVars, internal_enterBomPartMasterDataTouchesStart, internal_enterBomPartMasterDataTouchesEnd} from '../logging'
import { IGlobalVars } from '../global-vars';
import { GlobalFunc } from '../global-func';
import { dc_mc_FrontPanel01, adc_mc_FrontPanel01 } from '../modules/mc_FrontPanel01'
import { dc_mc_Drawer01, adc_mc_Drawer01 } from '../modules/mc_Drawer01'
import { dc_mc_Handle01, adc_mc_Handle01 } from '../modules/mc_Handle01'
import { dc_mc_DrawerBox01, adc_mc_DrawerBox01 } from '../modules/mc_DrawerBox01'
import { dc_mc_Hinge01, adc_mc_Hinge01 } from '../modules/mc_Hinge01'
import { dc_mc_Leg01, adc_mc_Leg01 } from '../modules/mc_Leg01'
import { dc_mr_Paneltop, adc_mr_Paneltop } from '../modules/mr_Paneltop'
import { dc_mc_Panel01, adc_mc_Panel01 } from '../modules/mc_Panel01'
import { dc_mf_Drawer, adc_mf_Drawer } from '../modules/mf_Drawer'
import { dc_mc_PlinthArea01, adc_mc_PlinthArea01 } from '../modules/mc_PlinthArea01'
import { dc_mr_StorageunitSingle, adc_mr_StorageunitSingle } from '../modules/mr_StorageunitSingle'
import { dc_mc_FrontPanelGlass01, adc_mc_FrontPanelGlass01 } from '../modules/mc_FrontPanelGlass01'
import { dc_mc_LightSystem01, adc_mc_LightSystem01 } from '../modules/mc_LightSystem01'
import { dc_mc_HangerSystem01, adc_mc_HangerSystem01 } from '../modules/mc_HangerSystem01'
import { dc_mf_Fliplift, adc_mf_Fliplift } from '../modules/mf_Fliplift'
import { dc_mc_Fliplift01, adc_mc_Fliplift01 } from '../modules/mc_Fliplift01'
import { dc_mf_Door, adc_mf_Door } from '../modules/mf_Door'
import { dc_mc_Door01, adc_mc_Door01 } from '../modules/mc_Door01'
import { dc_mr_CornerunitStraight, adc_mr_CornerunitStraight } from '../modules/mr_CornerunitStraight'
import { dc_mc_ShelfadjGroup01, adc_mc_ShelfadjGroup01 } from '../modules/mc_ShelfadjGroup01'
import { dc_mc_ShelfadjWood01, adc_mc_ShelfadjWood01 } from '../modules/mc_ShelfadjWood01'
import { dc_mc_ShelfadjGlass01, adc_mc_ShelfadjGlass01 } from '../modules/mc_ShelfadjGlass01'
import { dc_mc_ShelfadjDrill01, adc_mc_ShelfadjDrill01 } from '../modules/mc_ShelfadjDrill01'
import { dc_mc_ThermoformedPanel01, adc_mc_ThermoformedPanel01 } from '../modules/mc_ThermoformedPanel01'
import { dc_mc_MetalFrame01, adc_mc_MetalFrame01 } from '../modules/mc_MetalFrame01'
import { dc_mc_WoodFrame01, adc_mc_WoodFrame01 } from '../modules/mc_WoodFrame01'
import { dc_mc_Storageunit01, adc_mc_Storageunit01 } from '../modules/mc_Storageunit01'
import { dc_mc_Handlestrip01, adc_mc_Handlestrip01 } from '../modules/mc_Handlestrip01'
import { dc_mc_StorageunitSidepanel01, adc_mc_StorageunitSidepanel01 } from '../modules/mc_StorageunitSidepanel01'
import { dc_mc_StorageunitShelfbtm01, adc_mc_StorageunitShelfbtm01 } from '../modules/mc_StorageunitShelfbtm01'
import { dc_mc_StorageunitShelftop01, adc_mc_StorageunitShelftop01 } from '../modules/mc_StorageunitShelftop01'
import { dc_mc_StorageunitBackwall01, adc_mc_StorageunitBackwall01 } from '../modules/mc_StorageunitBackwall01'
import { dc_mc_StorageunitShelffixed01, adc_mc_StorageunitShelffixed01 } from '../modules/mc_StorageunitShelffixed01'
import { dc_mc_CleatVert01, adc_mc_CleatVert01 } from '../modules/mc_CleatVert01'
import { dc_mc_Panelblind01, adc_mc_Panelblind01 } from '../modules/mc_Panelblind01'
import { dc_mc_CornerunitStraight01, adc_mc_CornerunitStraight01 } from '../modules/mc_CornerunitStraight01'
import { dc_mc_ShelfadjFitting01, adc_mc_ShelfadjFitting01 } from '../modules/mc_ShelfadjFitting01'
import { dc_mf_Oven, adc_mf_Oven } from '../modules/mf_Oven'
import { dc_mc_Oven01, adc_mc_Oven01 } from '../modules/mc_Oven01'
import { dc_mf_Fridge, adc_mf_Fridge } from '../modules/mf_Fridge'
import { dc_mf_RackArea, adc_mf_RackArea } from '../modules/mf_RackArea'
import { dc_mc_RackArea01, adc_mc_RackArea01 } from '../modules/mc_RackArea01'
import { dc_mc_ShelffixedGroup01, adc_mc_ShelffixedGroup01 } from '../modules/mc_ShelffixedGroup01'
import { dc_mc_DoorGroup01, adc_mc_DoorGroup01 } from '../modules/mc_DoorGroup01'
import { dc_mc_VertDivider01, adc_mc_VertDivider01 } from '../modules/mc_VertDivider01'
import { dc_mc_Duststrip01, adc_mc_Duststrip01 } from '../modules/mc_Duststrip01'
import { dc_mr_Upright, adc_mr_Upright } from '../modules/mr_Upright'
import { dc_mc_Upright01, adc_mc_Upright01 } from '../modules/mc_Upright01'
import { dc_mr_Countertop, adc_mr_Countertop } from '../modules/mr_Countertop'
import { dc_mc_Countertop01, adc_mc_Countertop01 } from '../modules/mc_Countertop01'
import { dc_mr_Backsplash, adc_mr_Backsplash } from '../modules/mr_Backsplash'
import { dc_mc_Backsplash, adc_mc_Backsplash } from '../modules/mc_Backsplash'
import { dc_mr_Toekick, adc_mr_Toekick } from '../modules/mr_Toekick'
import { dc_mc_Toekick, adc_mc_Toekick } from '../modules/mc_Toekick'
import { dc_mc_Pushtoopen01, adc_mc_Pushtoopen01 } from '../modules/mc_Pushtoopen01'
import { dc_mc_PanelWoodFrame01, adc_mc_PanelWoodFrame01 } from '../modules/mc_PanelWoodFrame01'
import { dc_mc_HingeGroup01, adc_mc_HingeGroup01 } from '../modules/mc_HingeGroup01'
import { dc_mc_FlipliftHardware01, adc_mc_FlipliftHardware01 } from '../modules/mc_FlipliftHardware01'
import { dc_mr_Fingergrip, adc_mr_Fingergrip } from '../modules/mr_Fingergrip'
import { dc_mf_Fixedfront, adc_mf_Fixedfront } from '../modules/mf_Fixedfront'
import { dc_mc_Fixedfront01, adc_mc_Fixedfront01 } from '../modules/mc_Fixedfront01'
import { dc_mc_StorageunitShelftop02, adc_mc_StorageunitShelftop02 } from '../modules/mc_StorageunitShelftop02'
import { dc_mc_StorageunitShelftop03, adc_mc_StorageunitShelftop03 } from '../modules/mc_StorageunitShelftop03'
import { dc_mc_StorageunitShelftop04, adc_mc_StorageunitShelftop04 } from '../modules/mc_StorageunitShelftop04'
import { dc_mc_Fingergrip01, adc_mc_Fingergrip01 } from '../modules/mc_Fingergrip01'
import { dc_mc_Fridge01, adc_mc_Fridge01 } from '../modules/mc_Fridge01'
import { dc_mc_ApplianceGraphic, adc_mc_ApplianceGraphic } from '../modules/mc_ApplianceGraphic'
import { dc_mr_Hood, adc_mr_Hood } from '../modules/mr_Hood'
import { dc_mc_Paneltop01, adc_mc_Paneltop01 } from '../modules/mc_Paneltop01'
import { dc_mf_Hob, adc_mf_Hob } from '../modules/mf_Hob'
import { dc_mc_Hob01, adc_mc_Hob01 } from '../modules/mc_Hob01'
import { dc_mc_Sink01, adc_mc_Sink01 } from '../modules/mc_Sink01'
import { dc_mf_Sink, adc_mf_Sink } from '../modules/mf_Sink'
import { dc_mr_Filler01, adc_mr_Filler01 } from '../modules/mr_Filler01'
import { dc_mf_FillerFront, adc_mf_FillerFront } from '../modules/mf_FillerFront'
import { dc_mc_FillerFront01, adc_mc_FillerFront01 } from '../modules/mc_FillerFront01'
import { dc_mr_Appliance, adc_mr_Appliance } from '../modules/mr_Appliance'
import { dc_mc_Dishwasher, adc_mc_Dishwasher } from '../modules/mc_Dishwasher'
import { dc_mf_Dishwasher, adc_mf_Dishwasher } from '../modules/mf_Dishwasher'
import { dc_mr_CornerFiller, adc_mr_CornerFiller } from '../modules/mr_CornerFiller'
import { dc_mc_Cornerunit01, adc_mc_Cornerunit01 } from '../modules/mc_Cornerunit01'
import { dc_mr_IslandBackwall, adc_mr_IslandBackwall } from '../modules/mr_IslandBackwall'
import { dc_mr_Shelves, adc_mr_Shelves } from '../modules/mr_Shelves'
import { dc_mc_Shelves01, adc_mc_Shelves01 } from '../modules/mc_Shelves01'
import { dc_mc_Bracket01, adc_mc_Bracket01 } from '../modules/mc_Bracket01'
import { dc_mf_CornerFillerFront, adc_mf_CornerFillerFront } from '../modules/mf_CornerFillerFront'
import { dc_mc_CornerFillerFront01, adc_mc_CornerFillerFront01 } from '../modules/mc_CornerFillerFront01'

export interface cti_tab_HingePosition {
  readonly in_TypeElement? : string;
  readonly in_FrontDesign? : string;
  readonly in_AdditionalInfo1? : string;
  readonly in_AdditionalInfo2? : string;
  readonly in_AdditionalInfo3? : string;
  readonly in_FrameWidthMin? : number;
  readonly in_FrameWidthMax? : number;
  readonly in_FrontHeightMin? : number;
  readonly in_FrontHeightMax? : number;
  readonly in_FrontWidthMin? : number;
  readonly in_FrontWidthMax? : number;
  readonly in_WeightMax? : number;
  readonly in_FingergripTypeTop? : string;
  readonly in_FingergripTypeBtm? : string;
  readonly in_HandleDesign? : string;
  readonly in_HandlePosType? : string;
}

export interface ctm_tab_HingePosition {
}

export interface cto_tab_HingePosition extends ctm_tab_HingePosition {
  readonly _id : number;
  readonly Descriptor? : string;
  readonly TableSequence : number;
}

export interface ICT_tab_HingePosition
extends cti_tab_HingePosition, cto_tab_HingePosition {}

export class ct2_tab_HingePosition {

public findExactly(
     in_TypeElement: string|undefined,
     in_FrontDesign: string|undefined,
     in_AdditionalInfo1: string|undefined,
     in_AdditionalInfo2: string|undefined,
     in_AdditionalInfo3: string|undefined,
     in_FrameWidthMin: number|undefined,
     in_FrameWidthMax: number|undefined,
     in_FrontHeightMin: number|undefined,
     in_FrontHeightMax: number|undefined,
     in_FrontWidthMin: number|undefined,
     in_FrontWidthMax: number|undefined,
     in_WeightMax: number|undefined,
     in_FingergripTypeTop: string|undefined,
     in_FingergripTypeBtm: string|undefined,
     in_HandleDesign: string|undefined,
     in_HandlePosType: string|undefined,
): cto_tab_HingePosition | undefined {
  const res = ct_tab_HingePosition.find((p) => 
p.in_TypeElement === in_TypeElement
 && p.in_FrontDesign === in_FrontDesign
 && p.in_AdditionalInfo1 === in_AdditionalInfo1
 && p.in_AdditionalInfo2 === in_AdditionalInfo2
 && p.in_AdditionalInfo3 === in_AdditionalInfo3
 && p.in_FrameWidthMin === in_FrameWidthMin
 && p.in_FrameWidthMax === in_FrameWidthMax
 && p.in_FrontHeightMin === in_FrontHeightMin
 && p.in_FrontHeightMax === in_FrontHeightMax
 && p.in_FrontWidthMin === in_FrontWidthMin
 && p.in_FrontWidthMax === in_FrontWidthMax
 && p.in_WeightMax === in_WeightMax
 && p.in_FingergripTypeTop === in_FingergripTypeTop
 && p.in_FingergripTypeBtm === in_FingergripTypeBtm
 && p.in_HandleDesign === in_HandleDesign
 && p.in_HandlePosType === in_HandlePosType
);
return res;
}

public find(
predicate: (value: cti_tab_HingePosition) => boolean
): cto_tab_HingePosition | undefined {
  for (let index = 0; index < ct_tab_HingePosition.length; index++){
    const element = ct_tab_HingePosition[index];
    if(predicate(element)) return element;
  }
  return undefined;
}
}

export var ct_tab_HingePosition :ICT_tab_HingePosition[] = [
{
 _id: 1342,
 in_TypeElement: "All",
 in_FrontDesign: "All",
 in_AdditionalInfo1: "All",
 in_AdditionalInfo2: "All",
 in_AdditionalInfo3: "All",
 in_FrameWidthMin: 0,
 in_FrameWidthMax: 9999,
 in_FrontHeightMin: 0,
 in_FrontHeightMax: 750,
 in_FrontWidthMin: 0,
 in_FrontWidthMax: 700,
 in_WeightMax: 6,
 in_FingergripTypeTop: "NoFingergrip",
 in_FingergripTypeBtm: "NoFingergrip",
 in_HandleDesign: "All",
 in_HandlePosType: "All",
 Descriptor: "80mm_1_80mm",
 TableSequence: 1
}
,{
 _id: 1343,
 in_TypeElement: "All",
 in_FrontDesign: "All",
 in_AdditionalInfo1: "All",
 in_AdditionalInfo2: "All",
 in_AdditionalInfo3: "All",
 in_FrameWidthMin: 0,
 in_FrameWidthMax: 9999,
 in_FrontHeightMin: 750,
 in_FrontHeightMax: 1500,
 in_FrontWidthMin: 0,
 in_FrontWidthMax: 700,
 in_WeightMax: 12,
 in_FingergripTypeTop: "NoFingergrip",
 in_FingergripTypeBtm: "NoFingergrip",
 in_HandleDesign: "All",
 in_HandlePosType: "All",
 Descriptor: "80mm_1_1_80mm",
 TableSequence: 2
}
,{
 _id: 1344,
 in_TypeElement: "All",
 in_FrontDesign: "All",
 in_AdditionalInfo1: "All",
 in_AdditionalInfo2: "All",
 in_AdditionalInfo3: "All",
 in_FrameWidthMin: 0,
 in_FrameWidthMax: 9999,
 in_FrontHeightMin: 1500,
 in_FrontHeightMax: 2100,
 in_FrontWidthMin: 0,
 in_FrontWidthMax: 700,
 in_WeightMax: 17,
 in_FingergripTypeTop: "NoFingergrip",
 in_FingergripTypeBtm: "NoFingergrip",
 in_HandleDesign: "All",
 in_HandlePosType: "All",
 Descriptor: "80mm_1_1_1_80mm",
 TableSequence: 3
}
,{
 _id: 1345,
 in_TypeElement: "All",
 in_FrontDesign: "All",
 in_AdditionalInfo1: "All",
 in_AdditionalInfo2: "All",
 in_AdditionalInfo3: "All",
 in_FrameWidthMin: 0,
 in_FrameWidthMax: 9999,
 in_FrontHeightMin: 2100,
 in_FrontHeightMax: 2500,
 in_FrontWidthMin: 0,
 in_FrontWidthMax: 700,
 in_WeightMax: 22,
 in_FingergripTypeTop: "NoFingergrip",
 in_FingergripTypeBtm: "NoFingergrip",
 in_HandleDesign: "All",
 in_HandlePosType: "All",
 Descriptor: "80mm_1_1_1_1_80mm",
 TableSequence: 4
}
,{
 _id: 1346,
 in_TypeElement: "All",
 in_FrontDesign: "All",
 in_AdditionalInfo1: "All",
 in_AdditionalInfo2: "All",
 in_AdditionalInfo3: "All",
 in_FrameWidthMin: 0,
 in_FrameWidthMax: 9999,
 in_FrontHeightMin: 2500,
 in_FrontHeightMax: 3000,
 in_FrontWidthMin: 0,
 in_FrontWidthMax: 700,
 in_WeightMax: 28,
 in_FingergripTypeTop: "NoFingergrip",
 in_FingergripTypeBtm: "NoFingergrip",
 in_HandleDesign: "All",
 in_HandlePosType: "All",
 Descriptor: "80mm_1_1_1_1_1_80mm",
 TableSequence: 5
}
,{
 _id: 1347,
 in_TypeElement: "All",
 in_FrontDesign: "All",
 in_AdditionalInfo1: "All",
 in_AdditionalInfo2: "All",
 in_AdditionalInfo3: "All",
 in_FrameWidthMin: 0,
 in_FrameWidthMax: 9999,
 in_FrontHeightMin: 0,
 in_FrontHeightMax: 750,
 in_FrontWidthMin: 0,
 in_FrontWidthMax: 700,
 in_WeightMax: 6,
 in_FingergripTypeTop: "Metal",
 in_FingergripTypeBtm: "NoFingergrip",
 in_HandleDesign: "All",
 in_HandlePosType: "All",
 Descriptor: "80mm_1_80mm",
 TableSequence: 10
}
,{
 _id: 1348,
 in_TypeElement: "All",
 in_FrontDesign: "All",
 in_AdditionalInfo1: "All",
 in_AdditionalInfo2: "All",
 in_AdditionalInfo3: "All",
 in_FrameWidthMin: 0,
 in_FrameWidthMax: 9999,
 in_FrontHeightMin: 750,
 in_FrontHeightMax: 1500,
 in_FrontWidthMin: 0,
 in_FrontWidthMax: 700,
 in_WeightMax: 12,
 in_FingergripTypeTop: "Metal",
 in_FingergripTypeBtm: "NoFingergrip",
 in_HandleDesign: "All",
 in_HandlePosType: "All",
 Descriptor: "80mm_1_1_80mm",
 TableSequence: 11
}
,{
 _id: 1349,
 in_TypeElement: "All",
 in_FrontDesign: "All",
 in_AdditionalInfo1: "All",
 in_AdditionalInfo2: "All",
 in_AdditionalInfo3: "All",
 in_FrameWidthMin: 0,
 in_FrameWidthMax: 9999,
 in_FrontHeightMin: 1500,
 in_FrontHeightMax: 2100,
 in_FrontWidthMin: 0,
 in_FrontWidthMax: 700,
 in_WeightMax: 17,
 in_FingergripTypeTop: "Metal",
 in_FingergripTypeBtm: "NoFingergrip",
 in_HandleDesign: "All",
 in_HandlePosType: "All",
 Descriptor: "80mm_1_1_1_80mm",
 TableSequence: 12
}
,{
 _id: 1350,
 in_TypeElement: "All",
 in_FrontDesign: "All",
 in_AdditionalInfo1: "All",
 in_AdditionalInfo2: "All",
 in_AdditionalInfo3: "All",
 in_FrameWidthMin: 0,
 in_FrameWidthMax: 9999,
 in_FrontHeightMin: 2100,
 in_FrontHeightMax: 2500,
 in_FrontWidthMin: 0,
 in_FrontWidthMax: 700,
 in_WeightMax: 22,
 in_FingergripTypeTop: "Metal",
 in_FingergripTypeBtm: "NoFingergrip",
 in_HandleDesign: "All",
 in_HandlePosType: "All",
 Descriptor: "80mm_1_1_1_1_80mm",
 TableSequence: 13
}
,{
 _id: 1351,
 in_TypeElement: "All",
 in_FrontDesign: "All",
 in_AdditionalInfo1: "All",
 in_AdditionalInfo2: "All",
 in_AdditionalInfo3: "All",
 in_FrameWidthMin: 0,
 in_FrameWidthMax: 9999,
 in_FrontHeightMin: 2500,
 in_FrontHeightMax: 3000,
 in_FrontWidthMin: 0,
 in_FrontWidthMax: 700,
 in_WeightMax: 28,
 in_FingergripTypeTop: "Metal",
 in_FingergripTypeBtm: "NoFingergrip",
 in_HandleDesign: "All",
 in_HandlePosType: "All",
 Descriptor: "80mm_1_1_1_1_1_80mm",
 TableSequence: 14
}
,{
 _id: 1352,
 in_TypeElement: "All",
 in_FrontDesign: "All",
 in_AdditionalInfo1: "All",
 in_AdditionalInfo2: "All",
 in_AdditionalInfo3: "All",
 in_FrameWidthMin: 0,
 in_FrameWidthMax: 9999,
 in_FrontHeightMin: 0,
 in_FrontHeightMax: 750,
 in_FrontWidthMin: 0,
 in_FrontWidthMax: 700,
 in_WeightMax: 6,
 in_FingergripTypeTop: "Wood",
 in_FingergripTypeBtm: "NoFingergrip",
 in_HandleDesign: "All",
 in_HandlePosType: "All",
 Descriptor: "80mm_1_80mm",
 TableSequence: 21
}
,{
 _id: 1353,
 in_TypeElement: "All",
 in_FrontDesign: "All",
 in_AdditionalInfo1: "All",
 in_AdditionalInfo2: "All",
 in_AdditionalInfo3: "All",
 in_FrameWidthMin: 0,
 in_FrameWidthMax: 9999,
 in_FrontHeightMin: 750,
 in_FrontHeightMax: 1500,
 in_FrontWidthMin: 0,
 in_FrontWidthMax: 700,
 in_WeightMax: 12,
 in_FingergripTypeTop: "Wood",
 in_FingergripTypeBtm: "NoFingergrip",
 in_HandleDesign: "All",
 in_HandlePosType: "All",
 Descriptor: "80mm_1_1_80mm",
 TableSequence: 22
}
,{
 _id: 1354,
 in_TypeElement: "All",
 in_FrontDesign: "All",
 in_AdditionalInfo1: "All",
 in_AdditionalInfo2: "All",
 in_AdditionalInfo3: "All",
 in_FrameWidthMin: 0,
 in_FrameWidthMax: 9999,
 in_FrontHeightMin: 1500,
 in_FrontHeightMax: 2100,
 in_FrontWidthMin: 0,
 in_FrontWidthMax: 700,
 in_WeightMax: 17,
 in_FingergripTypeTop: "Wood",
 in_FingergripTypeBtm: "NoFingergrip",
 in_HandleDesign: "All",
 in_HandlePosType: "All",
 Descriptor: "80mm_1_1_1_80mm",
 TableSequence: 23
}
,{
 _id: 1355,
 in_TypeElement: "All",
 in_FrontDesign: "All",
 in_AdditionalInfo1: "All",
 in_AdditionalInfo2: "All",
 in_AdditionalInfo3: "All",
 in_FrameWidthMin: 0,
 in_FrameWidthMax: 9999,
 in_FrontHeightMin: 2100,
 in_FrontHeightMax: 2500,
 in_FrontWidthMin: 0,
 in_FrontWidthMax: 700,
 in_WeightMax: 22,
 in_FingergripTypeTop: "Wood",
 in_FingergripTypeBtm: "NoFingergrip",
 in_HandleDesign: "All",
 in_HandlePosType: "All",
 Descriptor: "80mm_1_1_1_1_80mm",
 TableSequence: 24
}
,{
 _id: 1356,
 in_TypeElement: "All",
 in_FrontDesign: "All",
 in_AdditionalInfo1: "All",
 in_AdditionalInfo2: "All",
 in_AdditionalInfo3: "All",
 in_FrameWidthMin: 0,
 in_FrameWidthMax: 9999,
 in_FrontHeightMin: 2500,
 in_FrontHeightMax: 3000,
 in_FrontWidthMin: 0,
 in_FrontWidthMax: 700,
 in_WeightMax: 28,
 in_FingergripTypeTop: "Wood",
 in_FingergripTypeBtm: "NoFingergrip",
 in_HandleDesign: "All",
 in_HandlePosType: "All",
 Descriptor: "80mm_1_1_1_1_1_80mm",
 TableSequence: 25
}
,{
 _id: 1357,
 in_TypeElement: "All",
 in_FrontDesign: "All",
 in_AdditionalInfo1: "All",
 in_AdditionalInfo2: "All",
 in_AdditionalInfo3: "All",
 in_FrameWidthMin: 0,
 in_FrameWidthMax: 9999,
 in_FrontHeightMin: 0,
 in_FrontHeightMax: 750,
 in_FrontWidthMin: 0,
 in_FrontWidthMax: 700,
 in_WeightMax: 6,
 in_FingergripTypeTop: "Metal",
 in_FingergripTypeBtm: "Metal",
 in_HandleDesign: "All",
 in_HandlePosType: "All",
 Descriptor: "80mm_1_80mm",
 TableSequence: 31
}
,{
 _id: 1358,
 in_TypeElement: "All",
 in_FrontDesign: "All",
 in_AdditionalInfo1: "All",
 in_AdditionalInfo2: "All",
 in_AdditionalInfo3: "All",
 in_FrameWidthMin: 0,
 in_FrameWidthMax: 9999,
 in_FrontHeightMin: 750,
 in_FrontHeightMax: 1500,
 in_FrontWidthMin: 0,
 in_FrontWidthMax: 700,
 in_WeightMax: 12,
 in_FingergripTypeTop: "Metal",
 in_FingergripTypeBtm: "Metal",
 in_HandleDesign: "All",
 in_HandlePosType: "All",
 Descriptor: "80mm_1_1_80mm",
 TableSequence: 32
}
,{
 _id: 1359,
 in_TypeElement: "All",
 in_FrontDesign: "All",
 in_AdditionalInfo1: "All",
 in_AdditionalInfo2: "All",
 in_AdditionalInfo3: "All",
 in_FrameWidthMin: 0,
 in_FrameWidthMax: 9999,
 in_FrontHeightMin: 1500,
 in_FrontHeightMax: 2100,
 in_FrontWidthMin: 0,
 in_FrontWidthMax: 700,
 in_WeightMax: 17,
 in_FingergripTypeTop: "Metal",
 in_FingergripTypeBtm: "Metal",
 in_HandleDesign: "All",
 in_HandlePosType: "All",
 Descriptor: "80mm_1_1_1_80mm",
 TableSequence: 33
}
,{
 _id: 1360,
 in_TypeElement: "All",
 in_FrontDesign: "All",
 in_AdditionalInfo1: "All",
 in_AdditionalInfo2: "All",
 in_AdditionalInfo3: "All",
 in_FrameWidthMin: 0,
 in_FrameWidthMax: 9999,
 in_FrontHeightMin: 2100,
 in_FrontHeightMax: 2500,
 in_FrontWidthMin: 0,
 in_FrontWidthMax: 700,
 in_WeightMax: 22,
 in_FingergripTypeTop: "Metal",
 in_FingergripTypeBtm: "Metal",
 in_HandleDesign: "All",
 in_HandlePosType: "All",
 Descriptor: "80mm_1_1_1_1_80mm",
 TableSequence: 34
}
,{
 _id: 1361,
 in_TypeElement: "All",
 in_FrontDesign: "All",
 in_AdditionalInfo1: "All",
 in_AdditionalInfo2: "All",
 in_AdditionalInfo3: "All",
 in_FrameWidthMin: 0,
 in_FrameWidthMax: 9999,
 in_FrontHeightMin: 2500,
 in_FrontHeightMax: 3000,
 in_FrontWidthMin: 0,
 in_FrontWidthMax: 700,
 in_WeightMax: 28,
 in_FingergripTypeTop: "Metal",
 in_FingergripTypeBtm: "Metal",
 in_HandleDesign: "All",
 in_HandlePosType: "All",
 Descriptor: "80mm_1_1_1_1_1_80mm",
 TableSequence: 35
}
,{
 _id: 1362,
 in_TypeElement: "All",
 in_FrontDesign: "All",
 in_AdditionalInfo1: "All",
 in_AdditionalInfo2: "All",
 in_AdditionalInfo3: "All",
 in_FrameWidthMin: 0,
 in_FrameWidthMax: 9999,
 in_FrontHeightMin: 0,
 in_FrontHeightMax: 750,
 in_FrontWidthMin: 0,
 in_FrontWidthMax: 700,
 in_WeightMax: 6,
 in_FingergripTypeTop: "NoFingergrip",
 in_FingergripTypeBtm: "Metal",
 in_HandleDesign: "All",
 in_HandlePosType: "All",
 Descriptor: "80mm_1_80mm",
 TableSequence: 41
}
,{
 _id: 1363,
 in_TypeElement: "All",
 in_FrontDesign: "All",
 in_AdditionalInfo1: "All",
 in_AdditionalInfo2: "All",
 in_AdditionalInfo3: "All",
 in_FrameWidthMin: 0,
 in_FrameWidthMax: 9999,
 in_FrontHeightMin: 750,
 in_FrontHeightMax: 1500,
 in_FrontWidthMin: 0,
 in_FrontWidthMax: 700,
 in_WeightMax: 12,
 in_FingergripTypeTop: "NoFingergrip",
 in_FingergripTypeBtm: "Metal",
 in_HandleDesign: "All",
 in_HandlePosType: "All",
 Descriptor: "80mm_1_1_80mm",
 TableSequence: 42
}
,{
 _id: 1364,
 in_TypeElement: "All",
 in_FrontDesign: "All",
 in_AdditionalInfo1: "All",
 in_AdditionalInfo2: "All",
 in_AdditionalInfo3: "All",
 in_FrameWidthMin: 0,
 in_FrameWidthMax: 9999,
 in_FrontHeightMin: 1500,
 in_FrontHeightMax: 2100,
 in_FrontWidthMin: 0,
 in_FrontWidthMax: 700,
 in_WeightMax: 17,
 in_FingergripTypeTop: "NoFingergrip",
 in_FingergripTypeBtm: "Metal",
 in_HandleDesign: "All",
 in_HandlePosType: "All",
 Descriptor: "80mm_1_1_1_80mm",
 TableSequence: 43
}
,{
 _id: 1365,
 in_TypeElement: "All",
 in_FrontDesign: "All",
 in_AdditionalInfo1: "All",
 in_AdditionalInfo2: "All",
 in_AdditionalInfo3: "All",
 in_FrameWidthMin: 0,
 in_FrameWidthMax: 9999,
 in_FrontHeightMin: 2100,
 in_FrontHeightMax: 2500,
 in_FrontWidthMin: 0,
 in_FrontWidthMax: 700,
 in_WeightMax: 22,
 in_FingergripTypeTop: "NoFingergrip",
 in_FingergripTypeBtm: "Metal",
 in_HandleDesign: "All",
 in_HandlePosType: "All",
 Descriptor: "80mm_1_1_1_1_80mm",
 TableSequence: 44
}
,{
 _id: 1366,
 in_TypeElement: "All",
 in_FrontDesign: "All",
 in_AdditionalInfo1: "All",
 in_AdditionalInfo2: "All",
 in_AdditionalInfo3: "All",
 in_FrameWidthMin: 0,
 in_FrameWidthMax: 9999,
 in_FrontHeightMin: 2500,
 in_FrontHeightMax: 3000,
 in_FrontWidthMin: 0,
 in_FrontWidthMax: 700,
 in_WeightMax: 28,
 in_FingergripTypeTop: "NoFingergrip",
 in_FingergripTypeBtm: "Metal",
 in_HandleDesign: "All",
 in_HandlePosType: "All",
 Descriptor: "80mm_1_1_1_1_1_80mm",
 TableSequence: 45
}
,{
 _id: 1367,
 in_TypeElement: "All",
 in_FrontDesign: "All",
 in_AdditionalInfo1: "All",
 in_AdditionalInfo2: "All",
 in_AdditionalInfo3: "All",
 in_FrameWidthMin: 0,
 in_FrameWidthMax: 9999,
 in_FrontHeightMin: 0,
 in_FrontHeightMax: 750,
 in_FrontWidthMin: 0,
 in_FrontWidthMax: 700,
 in_WeightMax: 6,
 in_FingergripTypeTop: "Wood",
 in_FingergripTypeBtm: "Wood",
 in_HandleDesign: "All",
 in_HandlePosType: "All",
 Descriptor: "80mm_1_80mm",
 TableSequence: 51
}
,{
 _id: 1368,
 in_TypeElement: "All",
 in_FrontDesign: "All",
 in_AdditionalInfo1: "All",
 in_AdditionalInfo2: "All",
 in_AdditionalInfo3: "All",
 in_FrameWidthMin: 0,
 in_FrameWidthMax: 9999,
 in_FrontHeightMin: 750,
 in_FrontHeightMax: 1500,
 in_FrontWidthMin: 0,
 in_FrontWidthMax: 700,
 in_WeightMax: 12,
 in_FingergripTypeTop: "Wood",
 in_FingergripTypeBtm: "Wood",
 in_HandleDesign: "All",
 in_HandlePosType: "All",
 Descriptor: "80mm_1_1_80mm",
 TableSequence: 52
}
,{
 _id: 1369,
 in_TypeElement: "All",
 in_FrontDesign: "All",
 in_AdditionalInfo1: "All",
 in_AdditionalInfo2: "All",
 in_AdditionalInfo3: "All",
 in_FrameWidthMin: 0,
 in_FrameWidthMax: 9999,
 in_FrontHeightMin: 1500,
 in_FrontHeightMax: 2100,
 in_FrontWidthMin: 0,
 in_FrontWidthMax: 700,
 in_WeightMax: 17,
 in_FingergripTypeTop: "Wood",
 in_FingergripTypeBtm: "Wood",
 in_HandleDesign: "All",
 in_HandlePosType: "All",
 Descriptor: "80mm_1_1_1_80mm",
 TableSequence: 53
}
,{
 _id: 1370,
 in_TypeElement: "All",
 in_FrontDesign: "All",
 in_AdditionalInfo1: "All",
 in_AdditionalInfo2: "All",
 in_AdditionalInfo3: "All",
 in_FrameWidthMin: 0,
 in_FrameWidthMax: 9999,
 in_FrontHeightMin: 2100,
 in_FrontHeightMax: 2500,
 in_FrontWidthMin: 0,
 in_FrontWidthMax: 700,
 in_WeightMax: 22,
 in_FingergripTypeTop: "Wood",
 in_FingergripTypeBtm: "Wood",
 in_HandleDesign: "All",
 in_HandlePosType: "All",
 Descriptor: "80mm_1_1_1_1_80mm",
 TableSequence: 54
}
,{
 _id: 1371,
 in_TypeElement: "All",
 in_FrontDesign: "All",
 in_AdditionalInfo1: "All",
 in_AdditionalInfo2: "All",
 in_AdditionalInfo3: "All",
 in_FrameWidthMin: 0,
 in_FrameWidthMax: 9999,
 in_FrontHeightMin: 2500,
 in_FrontHeightMax: 3000,
 in_FrontWidthMin: 0,
 in_FrontWidthMax: 700,
 in_WeightMax: 28,
 in_FingergripTypeTop: "Wood",
 in_FingergripTypeBtm: "Wood",
 in_HandleDesign: "All",
 in_HandlePosType: "All",
 Descriptor: "80mm_1_1_1_1_1_80mm",
 TableSequence: 55
}
,{
 _id: 1372,
 in_TypeElement: "All",
 in_FrontDesign: "All",
 in_AdditionalInfo1: "All",
 in_AdditionalInfo2: "All",
 in_AdditionalInfo3: "All",
 in_FrameWidthMin: 0,
 in_FrameWidthMax: 9999,
 in_FrontHeightMin: 0,
 in_FrontHeightMax: 750,
 in_FrontWidthMin: 0,
 in_FrontWidthMax: 700,
 in_WeightMax: 6,
 in_FingergripTypeTop: "NoFingergrip",
 in_FingergripTypeBtm: "Wood",
 in_HandleDesign: "All",
 in_HandlePosType: "All",
 Descriptor: "80mm_1_80mm",
 TableSequence: 61
}
,{
 _id: 1373,
 in_TypeElement: "All",
 in_FrontDesign: "All",
 in_AdditionalInfo1: "All",
 in_AdditionalInfo2: "All",
 in_AdditionalInfo3: "All",
 in_FrameWidthMin: 0,
 in_FrameWidthMax: 9999,
 in_FrontHeightMin: 750,
 in_FrontHeightMax: 1500,
 in_FrontWidthMin: 0,
 in_FrontWidthMax: 700,
 in_WeightMax: 12,
 in_FingergripTypeTop: "NoFingergrip",
 in_FingergripTypeBtm: "Wood",
 in_HandleDesign: "All",
 in_HandlePosType: "All",
 Descriptor: "80mm_1_1_80mm",
 TableSequence: 62
}
,{
 _id: 1374,
 in_TypeElement: "All",
 in_FrontDesign: "All",
 in_AdditionalInfo1: "All",
 in_AdditionalInfo2: "All",
 in_AdditionalInfo3: "All",
 in_FrameWidthMin: 0,
 in_FrameWidthMax: 9999,
 in_FrontHeightMin: 1500,
 in_FrontHeightMax: 2100,
 in_FrontWidthMin: 0,
 in_FrontWidthMax: 700,
 in_WeightMax: 17,
 in_FingergripTypeTop: "NoFingergrip",
 in_FingergripTypeBtm: "Wood",
 in_HandleDesign: "All",
 in_HandlePosType: "All",
 Descriptor: "80mm_1_1_1_80mm",
 TableSequence: 63
}
,{
 _id: 1375,
 in_TypeElement: "All",
 in_FrontDesign: "All",
 in_AdditionalInfo1: "All",
 in_AdditionalInfo2: "All",
 in_AdditionalInfo3: "All",
 in_FrameWidthMin: 0,
 in_FrameWidthMax: 9999,
 in_FrontHeightMin: 2100,
 in_FrontHeightMax: 2500,
 in_FrontWidthMin: 0,
 in_FrontWidthMax: 700,
 in_WeightMax: 22,
 in_FingergripTypeTop: "NoFingergrip",
 in_FingergripTypeBtm: "Wood",
 in_HandleDesign: "All",
 in_HandlePosType: "All",
 Descriptor: "80mm_1_1_1_1_80mm",
 TableSequence: 64
}
,{
 _id: 1376,
 in_TypeElement: "All",
 in_FrontDesign: "All",
 in_AdditionalInfo1: "All",
 in_AdditionalInfo2: "All",
 in_AdditionalInfo3: "All",
 in_FrameWidthMin: 0,
 in_FrameWidthMax: 9999,
 in_FrontHeightMin: 2500,
 in_FrontHeightMax: 3000,
 in_FrontWidthMin: 0,
 in_FrontWidthMax: 700,
 in_WeightMax: 28,
 in_FingergripTypeTop: "NoFingergrip",
 in_FingergripTypeBtm: "Wood",
 in_HandleDesign: "All",
 in_HandlePosType: "All",
 Descriptor: "80mm_1_1_1_1_1_80mm",
 TableSequence: 65
}
,{
 _id: 1377,
 in_TypeElement: "All",
 in_FrontDesign: "All",
 in_AdditionalInfo1: "All",
 in_AdditionalInfo2: "All",
 in_AdditionalInfo3: "All",
 in_FrameWidthMin: 0,
 in_FrameWidthMax: 9999,
 in_FrontHeightMin: 0,
 in_FrontHeightMax: 750,
 in_FrontWidthMin: 0,
 in_FrontWidthMax: 700,
 in_WeightMax: 6,
 in_FingergripTypeTop: "NoFingergrip",
 in_FingergripTypeBtm: "NoFingergrip",
 in_HandleDesign: "50",
 in_HandlePosType: "StripeBtm",
 Descriptor: "115mm_1_80mm",
 TableSequence: 71
}
,{
 _id: 1378,
 in_TypeElement: "All",
 in_FrontDesign: "All",
 in_AdditionalInfo1: "All",
 in_AdditionalInfo2: "All",
 in_AdditionalInfo3: "All",
 in_FrameWidthMin: 0,
 in_FrameWidthMax: 9999,
 in_FrontHeightMin: 750,
 in_FrontHeightMax: 1500,
 in_FrontWidthMin: 0,
 in_FrontWidthMax: 700,
 in_WeightMax: 12,
 in_FingergripTypeTop: "NoFingergrip",
 in_FingergripTypeBtm: "NoFingergrip",
 in_HandleDesign: "50",
 in_HandlePosType: "StripeBtm",
 Descriptor: "115mm_1_1_80mm",
 TableSequence: 72
}
,{
 _id: 1379,
 in_TypeElement: "All",
 in_FrontDesign: "All",
 in_AdditionalInfo1: "All",
 in_AdditionalInfo2: "All",
 in_AdditionalInfo3: "All",
 in_FrameWidthMin: 0,
 in_FrameWidthMax: 9999,
 in_FrontHeightMin: 1500,
 in_FrontHeightMax: 2100,
 in_FrontWidthMin: 0,
 in_FrontWidthMax: 700,
 in_WeightMax: 17,
 in_FingergripTypeTop: "NoFingergrip",
 in_FingergripTypeBtm: "NoFingergrip",
 in_HandleDesign: "50",
 in_HandlePosType: "StripeBtm",
 Descriptor: "115mm_1_1_1_80mm",
 TableSequence: 73
}
,{
 _id: 1380,
 in_TypeElement: "All",
 in_FrontDesign: "All",
 in_AdditionalInfo1: "All",
 in_AdditionalInfo2: "All",
 in_AdditionalInfo3: "All",
 in_FrameWidthMin: 0,
 in_FrameWidthMax: 9999,
 in_FrontHeightMin: 2100,
 in_FrontHeightMax: 2500,
 in_FrontWidthMin: 0,
 in_FrontWidthMax: 700,
 in_WeightMax: 22,
 in_FingergripTypeTop: "NoFingergrip",
 in_FingergripTypeBtm: "NoFingergrip",
 in_HandleDesign: "50",
 in_HandlePosType: "StripeBtm",
 Descriptor: "115mm_1_1_1_1_80mm",
 TableSequence: 74
}
,{
 _id: 1381,
 in_TypeElement: "All",
 in_FrontDesign: "All",
 in_AdditionalInfo1: "All",
 in_AdditionalInfo2: "All",
 in_AdditionalInfo3: "All",
 in_FrameWidthMin: 0,
 in_FrameWidthMax: 9999,
 in_FrontHeightMin: 2500,
 in_FrontHeightMax: 3000,
 in_FrontWidthMin: 0,
 in_FrontWidthMax: 700,
 in_WeightMax: 28,
 in_FingergripTypeTop: "NoFingergrip",
 in_FingergripTypeBtm: "NoFingergrip",
 in_HandleDesign: "50",
 in_HandlePosType: "StripeBtm",
 Descriptor: "115mm_1_1_1_1_1_80mm",
 TableSequence: 75
}
,{
 _id: 1382,
 in_TypeElement: "All",
 in_FrontDesign: "All",
 in_AdditionalInfo1: "All",
 in_AdditionalInfo2: "All",
 in_AdditionalInfo3: "All",
 in_FrameWidthMin: 0,
 in_FrameWidthMax: 9999,
 in_FrontHeightMin: 0,
 in_FrontHeightMax: 750,
 in_FrontWidthMin: 0,
 in_FrontWidthMax: 700,
 in_WeightMax: 6,
 in_FingergripTypeTop: "NoFingergrip",
 in_FingergripTypeBtm: "NoFingergrip",
 in_HandleDesign: "50",
 in_HandlePosType: "StripeTop",
 Descriptor: "80mm_1_115mm",
 TableSequence: 81
}
,{
 _id: 1383,
 in_TypeElement: "All",
 in_FrontDesign: "All",
 in_AdditionalInfo1: "All",
 in_AdditionalInfo2: "All",
 in_AdditionalInfo3: "All",
 in_FrameWidthMin: 0,
 in_FrameWidthMax: 9999,
 in_FrontHeightMin: 750,
 in_FrontHeightMax: 1500,
 in_FrontWidthMin: 0,
 in_FrontWidthMax: 700,
 in_WeightMax: 12,
 in_FingergripTypeTop: "NoFingergrip",
 in_FingergripTypeBtm: "NoFingergrip",
 in_HandleDesign: "50",
 in_HandlePosType: "StripeTop",
 Descriptor: "80mm_1_1_115mm",
 TableSequence: 82
}
,{
 _id: 1384,
 in_TypeElement: "All",
 in_FrontDesign: "All",
 in_AdditionalInfo1: "All",
 in_AdditionalInfo2: "All",
 in_AdditionalInfo3: "All",
 in_FrameWidthMin: 0,
 in_FrameWidthMax: 9999,
 in_FrontHeightMin: 1500,
 in_FrontHeightMax: 2100,
 in_FrontWidthMin: 0,
 in_FrontWidthMax: 700,
 in_WeightMax: 17,
 in_FingergripTypeTop: "NoFingergrip",
 in_FingergripTypeBtm: "NoFingergrip",
 in_HandleDesign: "50",
 in_HandlePosType: "StripeTop",
 Descriptor: "80mm_1_1_1_115mm",
 TableSequence: 83
}
,{
 _id: 1385,
 in_TypeElement: "All",
 in_FrontDesign: "All",
 in_AdditionalInfo1: "All",
 in_AdditionalInfo2: "All",
 in_AdditionalInfo3: "All",
 in_FrameWidthMin: 0,
 in_FrameWidthMax: 9999,
 in_FrontHeightMin: 2100,
 in_FrontHeightMax: 2500,
 in_FrontWidthMin: 0,
 in_FrontWidthMax: 700,
 in_WeightMax: 22,
 in_FingergripTypeTop: "NoFingergrip",
 in_FingergripTypeBtm: "NoFingergrip",
 in_HandleDesign: "50",
 in_HandlePosType: "StripeTop",
 Descriptor: "80mm_1_1_1_1_115mm",
 TableSequence: 84
}
,{
 _id: 1386,
 in_TypeElement: "All",
 in_FrontDesign: "All",
 in_AdditionalInfo1: "All",
 in_AdditionalInfo2: "All",
 in_AdditionalInfo3: "All",
 in_FrameWidthMin: 0,
 in_FrameWidthMax: 9999,
 in_FrontHeightMin: 2500,
 in_FrontHeightMax: 3000,
 in_FrontWidthMin: 0,
 in_FrontWidthMax: 700,
 in_WeightMax: 28,
 in_FingergripTypeTop: "NoFingergrip",
 in_FingergripTypeBtm: "NoFingergrip",
 in_HandleDesign: "50",
 in_HandlePosType: "StripeTop",
 Descriptor: "80mm_1_1_1_1_1_115mm",
 TableSequence: 85
}
,{
 _id: 1387,
 in_TypeElement: "BaseUnitSink",
 in_FrontDesign: "All",
 in_AdditionalInfo1: "All",
 in_AdditionalInfo2: "All",
 in_AdditionalInfo3: "All",
 in_FrameWidthMin: 0,
 in_FrameWidthMax: 9999,
 in_FrontHeightMin: 0,
 in_FrontHeightMax: 750,
 in_FrontWidthMin: 0,
 in_FrontWidthMax: 700,
 in_WeightMax: 6,
 in_FingergripTypeTop: "NoFingergrip",
 in_FingergripTypeBtm: "NoFingergrip",
 in_HandleDesign: "All",
 in_HandlePosType: "All",
 Descriptor: "80mm_1_170mm",
 TableSequence: 90
}
,{
 _id: 1388,
 in_TypeElement: "BaseUnitSink",
 in_FrontDesign: "All",
 in_AdditionalInfo1: "All",
 in_AdditionalInfo2: "All",
 in_AdditionalInfo3: "All",
 in_FrameWidthMin: 0,
 in_FrameWidthMax: 9999,
 in_FrontHeightMin: 750,
 in_FrontHeightMax: 1500,
 in_FrontWidthMin: 0,
 in_FrontWidthMax: 700,
 in_WeightMax: 12,
 in_FingergripTypeTop: "NoFingergrip",
 in_FingergripTypeBtm: "NoFingergrip",
 in_HandleDesign: "All",
 in_HandlePosType: "All",
 Descriptor: "80mm_1_1_170mm",
 TableSequence: 91
}
,{
 _id: 1389,
 in_TypeElement: "BaseUnitSink",
 in_FrontDesign: "All",
 in_AdditionalInfo1: "All",
 in_AdditionalInfo2: "All",
 in_AdditionalInfo3: "All",
 in_FrameWidthMin: 0,
 in_FrameWidthMax: 9999,
 in_FrontHeightMin: 1500,
 in_FrontHeightMax: 2100,
 in_FrontWidthMin: 0,
 in_FrontWidthMax: 700,
 in_WeightMax: 17,
 in_FingergripTypeTop: "NoFingergrip",
 in_FingergripTypeBtm: "NoFingergrip",
 in_HandleDesign: "All",
 in_HandlePosType: "All",
 Descriptor: "80mm_1_1_1_170mm",
 TableSequence: 92
}
,{
 _id: 1390,
 in_TypeElement: "BaseUnitSink",
 in_FrontDesign: "All",
 in_AdditionalInfo1: "All",
 in_AdditionalInfo2: "All",
 in_AdditionalInfo3: "All",
 in_FrameWidthMin: 0,
 in_FrameWidthMax: 9999,
 in_FrontHeightMin: 2100,
 in_FrontHeightMax: 2500,
 in_FrontWidthMin: 0,
 in_FrontWidthMax: 700,
 in_WeightMax: 22,
 in_FingergripTypeTop: "NoFingergrip",
 in_FingergripTypeBtm: "NoFingergrip",
 in_HandleDesign: "All",
 in_HandlePosType: "All",
 Descriptor: "80mm_1_1_1_1_170mm",
 TableSequence: 93
}
,{
 _id: 1391,
 in_TypeElement: "BaseUnitSink",
 in_FrontDesign: "All",
 in_AdditionalInfo1: "All",
 in_AdditionalInfo2: "All",
 in_AdditionalInfo3: "All",
 in_FrameWidthMin: 0,
 in_FrameWidthMax: 9999,
 in_FrontHeightMin: 2500,
 in_FrontHeightMax: 3000,
 in_FrontWidthMin: 0,
 in_FrontWidthMax: 700,
 in_WeightMax: 28,
 in_FingergripTypeTop: "NoFingergrip",
 in_FingergripTypeBtm: "NoFingergrip",
 in_HandleDesign: "All",
 in_HandlePosType: "All",
 Descriptor: "80mm_1_1_1_1_1_170mm",
 TableSequence: 94
}
,{
 _id: 1392,
 in_TypeElement: "All",
 in_FrontDesign: "All",
 in_AdditionalInfo1: "FHF",
 in_AdditionalInfo2: "Powerstorage",
 in_AdditionalInfo3: "All",
 in_FrameWidthMin: 0,
 in_FrameWidthMax: 9999,
 in_FrontHeightMin: 0,
 in_FrontHeightMax: 900,
 in_FrontWidthMin: 0,
 in_FrontWidthMax: 600,
 in_WeightMax: 6,
 in_FingergripTypeTop: "NoFingergrip",
 in_FingergripTypeBtm: "NoFingergrip",
 in_HandleDesign: "All",
 in_HandlePosType: "All",
 Descriptor: "80mm_1_80mm",
 TableSequence: 200
}
,{
 _id: 1393,
 in_TypeElement: "All",
 in_FrontDesign: "All",
 in_AdditionalInfo1: "FHF",
 in_AdditionalInfo2: "Powerstorage",
 in_AdditionalInfo3: "All",
 in_FrameWidthMin: 0,
 in_FrameWidthMax: 9999,
 in_FrontHeightMin: 0,
 in_FrontHeightMax: 900,
 in_FrontWidthMin: 600,
 in_FrontWidthMax: 1000,
 in_WeightMax: 12,
 in_FingergripTypeTop: "NoFingergrip",
 in_FingergripTypeBtm: "NoFingergrip",
 in_HandleDesign: "All",
 in_HandlePosType: "All",
 Descriptor: "80mm_1_1_80mm",
 TableSequence: 201
}
,{
 _id: 1394,
 in_TypeElement: "All",
 in_FrontDesign: "All",
 in_AdditionalInfo1: "FHF",
 in_AdditionalInfo2: "Powerstorage",
 in_AdditionalInfo3: "All",
 in_FrameWidthMin: 0,
 in_FrameWidthMax: 9999,
 in_FrontHeightMin: 0,
 in_FrontHeightMax: 900,
 in_FrontWidthMin: 1000,
 in_FrontWidthMax: 1400,
 in_WeightMax: 17,
 in_FingergripTypeTop: "NoFingergrip",
 in_FingergripTypeBtm: "NoFingergrip",
 in_HandleDesign: "All",
 in_HandlePosType: "All",
 Descriptor: "80mm_1_1_1_80mm",
 TableSequence: 202
}
,{
 _id: 1395,
 in_TypeElement: "All",
 in_FrontDesign: "All",
 in_AdditionalInfo1: "UF",
 in_AdditionalInfo2: "Gasspring",
 in_AdditionalInfo3: "All",
 in_FrameWidthMin: 0,
 in_FrameWidthMax: 9999,
 in_FrontHeightMin: 0,
 in_FrontHeightMax: 900,
 in_FrontWidthMin: 0,
 in_FrontWidthMax: 600,
 in_WeightMax: 6,
 in_FingergripTypeTop: "NoFingergrip",
 in_FingergripTypeBtm: "NoFingergrip",
 in_HandleDesign: "All",
 in_HandlePosType: "All",
 Descriptor: "80mm_1_80mm",
 TableSequence: 210
}
,{
 _id: 1396,
 in_TypeElement: "All",
 in_FrontDesign: "All",
 in_AdditionalInfo1: "UF",
 in_AdditionalInfo2: "Gasspring",
 in_AdditionalInfo3: "All",
 in_FrameWidthMin: 0,
 in_FrameWidthMax: 9999,
 in_FrontHeightMin: 0,
 in_FrontHeightMax: 900,
 in_FrontWidthMin: 600,
 in_FrontWidthMax: 1000,
 in_WeightMax: 12,
 in_FingergripTypeTop: "NoFingergrip",
 in_FingergripTypeBtm: "NoFingergrip",
 in_HandleDesign: "All",
 in_HandlePosType: "All",
 Descriptor: "80mm_1_1_80mm",
 TableSequence: 211
}
,{
 _id: 1397,
 in_TypeElement: "All",
 in_FrontDesign: "All",
 in_AdditionalInfo1: "UF",
 in_AdditionalInfo2: "Gasspring",
 in_AdditionalInfo3: "All",
 in_FrameWidthMin: 0,
 in_FrameWidthMax: 9999,
 in_FrontHeightMin: 0,
 in_FrontHeightMax: 900,
 in_FrontWidthMin: 1000,
 in_FrontWidthMax: 1400,
 in_WeightMax: 17,
 in_FingergripTypeTop: "NoFingergrip",
 in_FingergripTypeBtm: "NoFingergrip",
 in_HandleDesign: "All",
 in_HandlePosType: "All",
 Descriptor: "80mm_1_1_1_80mm",
 TableSequence: 212
}
,{
 _id: 1398,
 in_TypeElement: "All",
 in_FrontDesign: "All",
 in_AdditionalInfo1: "DF",
 in_AdditionalInfo2: "DropDownHinge",
 in_AdditionalInfo3: "All",
 in_FrameWidthMin: 0,
 in_FrameWidthMax: 9999,
 in_FrontHeightMin: 0,
 in_FrontHeightMax: 900,
 in_FrontWidthMin: 0,
 in_FrontWidthMax: 600,
 in_WeightMax: 6,
 in_FingergripTypeTop: "NoFingergrip",
 in_FingergripTypeBtm: "NoFingergrip",
 in_HandleDesign: "All",
 in_HandlePosType: "All",
 Descriptor: "80mm_1_80mm",
 TableSequence: 220
}
,{
 _id: 1399,
 in_TypeElement: "All",
 in_FrontDesign: "All",
 in_AdditionalInfo1: "DF",
 in_AdditionalInfo2: "DropDownHinge",
 in_AdditionalInfo3: "All",
 in_FrameWidthMin: 0,
 in_FrameWidthMax: 9999,
 in_FrontHeightMin: 0,
 in_FrontHeightMax: 900,
 in_FrontWidthMin: 600,
 in_FrontWidthMax: 1000,
 in_WeightMax: 12,
 in_FingergripTypeTop: "NoFingergrip",
 in_FingergripTypeBtm: "NoFingergrip",
 in_HandleDesign: "All",
 in_HandlePosType: "All",
 Descriptor: "80mm_1_1_80mm",
 TableSequence: 221
}
,{
 _id: 1400,
 in_TypeElement: "All",
 in_FrontDesign: "All",
 in_AdditionalInfo1: "DF",
 in_AdditionalInfo2: "DropDownHinge",
 in_AdditionalInfo3: "All",
 in_FrameWidthMin: 0,
 in_FrameWidthMax: 9999,
 in_FrontHeightMin: 0,
 in_FrontHeightMax: 900,
 in_FrontWidthMin: 1000,
 in_FrontWidthMax: 1400,
 in_WeightMax: 17,
 in_FingergripTypeTop: "NoFingergrip",
 in_FingergripTypeBtm: "NoFingergrip",
 in_HandleDesign: "All",
 in_HandlePosType: "All",
 Descriptor: "80mm_1_1_1_80mm",
 TableSequence: 222
}
,{
 _id: 1401,
 in_TypeElement: "All",
 in_FrontDesign: "WoodFrame",
 in_AdditionalInfo1: "All",
 in_AdditionalInfo2: "All",
 in_AdditionalInfo3: "WidthCoveredHeight",
 in_FrameWidthMin: 0,
 in_FrameWidthMax: 100,
 in_FrontHeightMin: 0,
 in_FrontHeightMax: 750,
 in_FrontWidthMin: 0,
 in_FrontWidthMax: 700,
 in_WeightMax: 6,
 in_FingergripTypeTop: "NoFingergrip",
 in_FingergripTypeBtm: "NoFingergrip",
 in_HandleDesign: "All",
 in_HandlePosType: "All",
 Descriptor: "140mm_1_140mm",
 TableSequence: 401
}
,{
 _id: 1402,
 in_TypeElement: "All",
 in_FrontDesign: "WoodFrame",
 in_AdditionalInfo1: "All",
 in_AdditionalInfo2: "All",
 in_AdditionalInfo3: "WidthCoveredHeight",
 in_FrameWidthMin: 0,
 in_FrameWidthMax: 100,
 in_FrontHeightMin: 750,
 in_FrontHeightMax: 1500,
 in_FrontWidthMin: 0,
 in_FrontWidthMax: 700,
 in_WeightMax: 12,
 in_FingergripTypeTop: "NoFingergrip",
 in_FingergripTypeBtm: "NoFingergrip",
 in_HandleDesign: "All",
 in_HandlePosType: "All",
 Descriptor: "140mm_1_1_140mm",
 TableSequence: 402
}
,{
 _id: 1403,
 in_TypeElement: "All",
 in_FrontDesign: "WoodFrame",
 in_AdditionalInfo1: "All",
 in_AdditionalInfo2: "All",
 in_AdditionalInfo3: "WidthCoveredHeight",
 in_FrameWidthMin: 0,
 in_FrameWidthMax: 100,
 in_FrontHeightMin: 1500,
 in_FrontHeightMax: 2100,
 in_FrontWidthMin: 0,
 in_FrontWidthMax: 700,
 in_WeightMax: 17,
 in_FingergripTypeTop: "NoFingergrip",
 in_FingergripTypeBtm: "NoFingergrip",
 in_HandleDesign: "All",
 in_HandlePosType: "All",
 Descriptor: "140mm_1_1_1_140mm",
 TableSequence: 403
}
,{
 _id: 1404,
 in_TypeElement: "All",
 in_FrontDesign: "WoodFrame",
 in_AdditionalInfo1: "All",
 in_AdditionalInfo2: "All",
 in_AdditionalInfo3: "WidthCoveredHeight",
 in_FrameWidthMin: 0,
 in_FrameWidthMax: 100,
 in_FrontHeightMin: 2100,
 in_FrontHeightMax: 2500,
 in_FrontWidthMin: 0,
 in_FrontWidthMax: 700,
 in_WeightMax: 22,
 in_FingergripTypeTop: "NoFingergrip",
 in_FingergripTypeBtm: "NoFingergrip",
 in_HandleDesign: "All",
 in_HandlePosType: "All",
 Descriptor: "140mm_1_1_1_1_140mm",
 TableSequence: 404
}
,{
 _id: 1405,
 in_TypeElement: "All",
 in_FrontDesign: "WoodFrame",
 in_AdditionalInfo1: "All",
 in_AdditionalInfo2: "All",
 in_AdditionalInfo3: "WidthCoveredHeight",
 in_FrameWidthMin: 0,
 in_FrameWidthMax: 100,
 in_FrontHeightMin: 2500,
 in_FrontHeightMax: 3000,
 in_FrontWidthMin: 0,
 in_FrontWidthMax: 700,
 in_WeightMax: 28,
 in_FingergripTypeTop: "NoFingergrip",
 in_FingergripTypeBtm: "NoFingergrip",
 in_HandleDesign: "All",
 in_HandlePosType: "All",
 Descriptor: "140mm_1_1_1_1_1_140mm",
 TableSequence: 405
}
,{
 _id: 1406,
 in_TypeElement: "All",
 in_FrontDesign: "WoodFrame",
 in_AdditionalInfo1: "All",
 in_AdditionalInfo2: "All",
 in_AdditionalInfo3: "WidthCoveredHeight",
 in_FrameWidthMin: 0,
 in_FrameWidthMax: 100,
 in_FrontHeightMin: 0,
 in_FrontHeightMax: 750,
 in_FrontWidthMin: 0,
 in_FrontWidthMax: 700,
 in_WeightMax: 6,
 in_FingergripTypeTop: "Metal",
 in_FingergripTypeBtm: "NoFingergrip",
 in_HandleDesign: "All",
 in_HandlePosType: "All",
 Descriptor: "140mm_1_140mm",
 TableSequence: 410
}
,{
 _id: 1407,
 in_TypeElement: "All",
 in_FrontDesign: "WoodFrame",
 in_AdditionalInfo1: "All",
 in_AdditionalInfo2: "All",
 in_AdditionalInfo3: "WidthCoveredHeight",
 in_FrameWidthMin: 0,
 in_FrameWidthMax: 100,
 in_FrontHeightMin: 750,
 in_FrontHeightMax: 1500,
 in_FrontWidthMin: 0,
 in_FrontWidthMax: 700,
 in_WeightMax: 12,
 in_FingergripTypeTop: "Metal",
 in_FingergripTypeBtm: "NoFingergrip",
 in_HandleDesign: "All",
 in_HandlePosType: "All",
 Descriptor: "140mm_1_1_140mm",
 TableSequence: 411
}
,{
 _id: 1408,
 in_TypeElement: "All",
 in_FrontDesign: "WoodFrame",
 in_AdditionalInfo1: "All",
 in_AdditionalInfo2: "All",
 in_AdditionalInfo3: "WidthCoveredHeight",
 in_FrameWidthMin: 0,
 in_FrameWidthMax: 100,
 in_FrontHeightMin: 1500,
 in_FrontHeightMax: 2100,
 in_FrontWidthMin: 0,
 in_FrontWidthMax: 700,
 in_WeightMax: 17,
 in_FingergripTypeTop: "Metal",
 in_FingergripTypeBtm: "NoFingergrip",
 in_HandleDesign: "All",
 in_HandlePosType: "All",
 Descriptor: "140mm_1_1_1_140mm",
 TableSequence: 412
}
,{
 _id: 1409,
 in_TypeElement: "All",
 in_FrontDesign: "WoodFrame",
 in_AdditionalInfo1: "All",
 in_AdditionalInfo2: "All",
 in_AdditionalInfo3: "WidthCoveredHeight",
 in_FrameWidthMin: 0,
 in_FrameWidthMax: 100,
 in_FrontHeightMin: 2100,
 in_FrontHeightMax: 2500,
 in_FrontWidthMin: 0,
 in_FrontWidthMax: 700,
 in_WeightMax: 22,
 in_FingergripTypeTop: "Metal",
 in_FingergripTypeBtm: "NoFingergrip",
 in_HandleDesign: "All",
 in_HandlePosType: "All",
 Descriptor: "140mm_1_1_1_1_140mm",
 TableSequence: 413
}
,{
 _id: 1410,
 in_TypeElement: "All",
 in_FrontDesign: "WoodFrame",
 in_AdditionalInfo1: "All",
 in_AdditionalInfo2: "All",
 in_AdditionalInfo3: "WidthCoveredHeight",
 in_FrameWidthMin: 0,
 in_FrameWidthMax: 100,
 in_FrontHeightMin: 2500,
 in_FrontHeightMax: 3000,
 in_FrontWidthMin: 0,
 in_FrontWidthMax: 700,
 in_WeightMax: 28,
 in_FingergripTypeTop: "Metal",
 in_FingergripTypeBtm: "NoFingergrip",
 in_HandleDesign: "All",
 in_HandlePosType: "All",
 Descriptor: "140mm_1_1_1_1_1_140mm",
 TableSequence: 414
}
,{
 _id: 1411,
 in_TypeElement: "All",
 in_FrontDesign: "WoodFrame",
 in_AdditionalInfo1: "All",
 in_AdditionalInfo2: "All",
 in_AdditionalInfo3: "WidthCoveredHeight",
 in_FrameWidthMin: 0,
 in_FrameWidthMax: 100,
 in_FrontHeightMin: 0,
 in_FrontHeightMax: 750,
 in_FrontWidthMin: 0,
 in_FrontWidthMax: 700,
 in_WeightMax: 6,
 in_FingergripTypeTop: "Wood",
 in_FingergripTypeBtm: "NoFingergrip",
 in_HandleDesign: "All",
 in_HandlePosType: "All",
 Descriptor: "140mm_1_140mm",
 TableSequence: 421
}
,{
 _id: 1412,
 in_TypeElement: "All",
 in_FrontDesign: "WoodFrame",
 in_AdditionalInfo1: "All",
 in_AdditionalInfo2: "All",
 in_AdditionalInfo3: "WidthCoveredHeight",
 in_FrameWidthMin: 0,
 in_FrameWidthMax: 100,
 in_FrontHeightMin: 750,
 in_FrontHeightMax: 1500,
 in_FrontWidthMin: 0,
 in_FrontWidthMax: 700,
 in_WeightMax: 12,
 in_FingergripTypeTop: "Wood",
 in_FingergripTypeBtm: "NoFingergrip",
 in_HandleDesign: "All",
 in_HandlePosType: "All",
 Descriptor: "140mm_1_1_140mm",
 TableSequence: 422
}
,{
 _id: 1413,
 in_TypeElement: "All",
 in_FrontDesign: "WoodFrame",
 in_AdditionalInfo1: "All",
 in_AdditionalInfo2: "All",
 in_AdditionalInfo3: "WidthCoveredHeight",
 in_FrameWidthMin: 0,
 in_FrameWidthMax: 100,
 in_FrontHeightMin: 1500,
 in_FrontHeightMax: 2100,
 in_FrontWidthMin: 0,
 in_FrontWidthMax: 700,
 in_WeightMax: 17,
 in_FingergripTypeTop: "Wood",
 in_FingergripTypeBtm: "NoFingergrip",
 in_HandleDesign: "All",
 in_HandlePosType: "All",
 Descriptor: "140mm_1_1_1_140mm",
 TableSequence: 423
}
,{
 _id: 1414,
 in_TypeElement: "All",
 in_FrontDesign: "WoodFrame",
 in_AdditionalInfo1: "All",
 in_AdditionalInfo2: "All",
 in_AdditionalInfo3: "WidthCoveredHeight",
 in_FrameWidthMin: 0,
 in_FrameWidthMax: 100,
 in_FrontHeightMin: 2100,
 in_FrontHeightMax: 2500,
 in_FrontWidthMin: 0,
 in_FrontWidthMax: 700,
 in_WeightMax: 22,
 in_FingergripTypeTop: "Wood",
 in_FingergripTypeBtm: "NoFingergrip",
 in_HandleDesign: "All",
 in_HandlePosType: "All",
 Descriptor: "140mm_1_1_1_1_140mm",
 TableSequence: 424
}
,{
 _id: 1415,
 in_TypeElement: "All",
 in_FrontDesign: "WoodFrame",
 in_AdditionalInfo1: "All",
 in_AdditionalInfo2: "All",
 in_AdditionalInfo3: "WidthCoveredHeight",
 in_FrameWidthMin: 0,
 in_FrameWidthMax: 100,
 in_FrontHeightMin: 2500,
 in_FrontHeightMax: 3000,
 in_FrontWidthMin: 0,
 in_FrontWidthMax: 700,
 in_WeightMax: 28,
 in_FingergripTypeTop: "Wood",
 in_FingergripTypeBtm: "NoFingergrip",
 in_HandleDesign: "All",
 in_HandlePosType: "All",
 Descriptor: "140mm_1_1_1_1_1_140mm",
 TableSequence: 425
}
,{
 _id: 1416,
 in_TypeElement: "All",
 in_FrontDesign: "WoodFrame",
 in_AdditionalInfo1: "All",
 in_AdditionalInfo2: "All",
 in_AdditionalInfo3: "WidthCoveredHeight",
 in_FrameWidthMin: 0,
 in_FrameWidthMax: 100,
 in_FrontHeightMin: 0,
 in_FrontHeightMax: 750,
 in_FrontWidthMin: 0,
 in_FrontWidthMax: 700,
 in_WeightMax: 6,
 in_FingergripTypeTop: "Metal",
 in_FingergripTypeBtm: "Metal",
 in_HandleDesign: "All",
 in_HandlePosType: "All",
 Descriptor: "140mm_1_140mm",
 TableSequence: 431
}
,{
 _id: 1417,
 in_TypeElement: "All",
 in_FrontDesign: "WoodFrame",
 in_AdditionalInfo1: "All",
 in_AdditionalInfo2: "All",
 in_AdditionalInfo3: "WidthCoveredHeight",
 in_FrameWidthMin: 0,
 in_FrameWidthMax: 100,
 in_FrontHeightMin: 750,
 in_FrontHeightMax: 1500,
 in_FrontWidthMin: 0,
 in_FrontWidthMax: 700,
 in_WeightMax: 12,
 in_FingergripTypeTop: "Metal",
 in_FingergripTypeBtm: "Metal",
 in_HandleDesign: "All",
 in_HandlePosType: "All",
 Descriptor: "140mm_1_1_140mm",
 TableSequence: 432
}
,{
 _id: 1418,
 in_TypeElement: "All",
 in_FrontDesign: "WoodFrame",
 in_AdditionalInfo1: "All",
 in_AdditionalInfo2: "All",
 in_AdditionalInfo3: "WidthCoveredHeight",
 in_FrameWidthMin: 0,
 in_FrameWidthMax: 100,
 in_FrontHeightMin: 1500,
 in_FrontHeightMax: 2100,
 in_FrontWidthMin: 0,
 in_FrontWidthMax: 700,
 in_WeightMax: 17,
 in_FingergripTypeTop: "Metal",
 in_FingergripTypeBtm: "Metal",
 in_HandleDesign: "All",
 in_HandlePosType: "All",
 Descriptor: "140mm_1_1_1_140mm",
 TableSequence: 433
}
,{
 _id: 1419,
 in_TypeElement: "All",
 in_FrontDesign: "WoodFrame",
 in_AdditionalInfo1: "All",
 in_AdditionalInfo2: "All",
 in_AdditionalInfo3: "WidthCoveredHeight",
 in_FrameWidthMin: 0,
 in_FrameWidthMax: 100,
 in_FrontHeightMin: 2100,
 in_FrontHeightMax: 2500,
 in_FrontWidthMin: 0,
 in_FrontWidthMax: 700,
 in_WeightMax: 22,
 in_FingergripTypeTop: "Metal",
 in_FingergripTypeBtm: "Metal",
 in_HandleDesign: "All",
 in_HandlePosType: "All",
 Descriptor: "140mm_1_1_1_1_140mm",
 TableSequence: 434
}
,{
 _id: 1420,
 in_TypeElement: "All",
 in_FrontDesign: "WoodFrame",
 in_AdditionalInfo1: "All",
 in_AdditionalInfo2: "All",
 in_AdditionalInfo3: "WidthCoveredHeight",
 in_FrameWidthMin: 0,
 in_FrameWidthMax: 100,
 in_FrontHeightMin: 2500,
 in_FrontHeightMax: 3000,
 in_FrontWidthMin: 0,
 in_FrontWidthMax: 700,
 in_WeightMax: 28,
 in_FingergripTypeTop: "Metal",
 in_FingergripTypeBtm: "Metal",
 in_HandleDesign: "All",
 in_HandlePosType: "All",
 Descriptor: "140mm_1_1_1_1_1_140mm",
 TableSequence: 435
}
,{
 _id: 1421,
 in_TypeElement: "All",
 in_FrontDesign: "WoodFrame",
 in_AdditionalInfo1: "All",
 in_AdditionalInfo2: "All",
 in_AdditionalInfo3: "WidthCoveredHeight",
 in_FrameWidthMin: 0,
 in_FrameWidthMax: 100,
 in_FrontHeightMin: 0,
 in_FrontHeightMax: 750,
 in_FrontWidthMin: 0,
 in_FrontWidthMax: 700,
 in_WeightMax: 6,
 in_FingergripTypeTop: "NoFingergrip",
 in_FingergripTypeBtm: "Metal",
 in_HandleDesign: "All",
 in_HandlePosType: "All",
 Descriptor: "140mm_1_140mm",
 TableSequence: 441
}
,{
 _id: 1422,
 in_TypeElement: "All",
 in_FrontDesign: "WoodFrame",
 in_AdditionalInfo1: "All",
 in_AdditionalInfo2: "All",
 in_AdditionalInfo3: "WidthCoveredHeight",
 in_FrameWidthMin: 0,
 in_FrameWidthMax: 100,
 in_FrontHeightMin: 750,
 in_FrontHeightMax: 1500,
 in_FrontWidthMin: 0,
 in_FrontWidthMax: 700,
 in_WeightMax: 12,
 in_FingergripTypeTop: "NoFingergrip",
 in_FingergripTypeBtm: "Metal",
 in_HandleDesign: "All",
 in_HandlePosType: "All",
 Descriptor: "140mm_1_1_140mm",
 TableSequence: 442
}
,{
 _id: 1423,
 in_TypeElement: "All",
 in_FrontDesign: "WoodFrame",
 in_AdditionalInfo1: "All",
 in_AdditionalInfo2: "All",
 in_AdditionalInfo3: "WidthCoveredHeight",
 in_FrameWidthMin: 0,
 in_FrameWidthMax: 100,
 in_FrontHeightMin: 1500,
 in_FrontHeightMax: 2100,
 in_FrontWidthMin: 0,
 in_FrontWidthMax: 700,
 in_WeightMax: 17,
 in_FingergripTypeTop: "NoFingergrip",
 in_FingergripTypeBtm: "Metal",
 in_HandleDesign: "All",
 in_HandlePosType: "All",
 Descriptor: "140mm_1_1_1_140mm",
 TableSequence: 443
}
,{
 _id: 1424,
 in_TypeElement: "All",
 in_FrontDesign: "WoodFrame",
 in_AdditionalInfo1: "All",
 in_AdditionalInfo2: "All",
 in_AdditionalInfo3: "WidthCoveredHeight",
 in_FrameWidthMin: 0,
 in_FrameWidthMax: 100,
 in_FrontHeightMin: 2100,
 in_FrontHeightMax: 2500,
 in_FrontWidthMin: 0,
 in_FrontWidthMax: 700,
 in_WeightMax: 22,
 in_FingergripTypeTop: "NoFingergrip",
 in_FingergripTypeBtm: "Metal",
 in_HandleDesign: "All",
 in_HandlePosType: "All",
 Descriptor: "140mm_1_1_1_1_140mm",
 TableSequence: 444
}
,{
 _id: 1425,
 in_TypeElement: "All",
 in_FrontDesign: "WoodFrame",
 in_AdditionalInfo1: "All",
 in_AdditionalInfo2: "All",
 in_AdditionalInfo3: "WidthCoveredHeight",
 in_FrameWidthMin: 0,
 in_FrameWidthMax: 100,
 in_FrontHeightMin: 2500,
 in_FrontHeightMax: 3000,
 in_FrontWidthMin: 0,
 in_FrontWidthMax: 700,
 in_WeightMax: 28,
 in_FingergripTypeTop: "NoFingergrip",
 in_FingergripTypeBtm: "Metal",
 in_HandleDesign: "All",
 in_HandlePosType: "All",
 Descriptor: "140mm_1_1_1_1_1_140mm",
 TableSequence: 445
}
,{
 _id: 1426,
 in_TypeElement: "All",
 in_FrontDesign: "WoodFrame",
 in_AdditionalInfo1: "All",
 in_AdditionalInfo2: "All",
 in_AdditionalInfo3: "WidthCoveredHeight",
 in_FrameWidthMin: 0,
 in_FrameWidthMax: 100,
 in_FrontHeightMin: 0,
 in_FrontHeightMax: 750,
 in_FrontWidthMin: 0,
 in_FrontWidthMax: 700,
 in_WeightMax: 6,
 in_FingergripTypeTop: "Wood",
 in_FingergripTypeBtm: "Wood",
 in_HandleDesign: "All",
 in_HandlePosType: "All",
 Descriptor: "140mm_1_140mm",
 TableSequence: 451
}
,{
 _id: 1427,
 in_TypeElement: "All",
 in_FrontDesign: "WoodFrame",
 in_AdditionalInfo1: "All",
 in_AdditionalInfo2: "All",
 in_AdditionalInfo3: "WidthCoveredHeight",
 in_FrameWidthMin: 0,
 in_FrameWidthMax: 100,
 in_FrontHeightMin: 750,
 in_FrontHeightMax: 1500,
 in_FrontWidthMin: 0,
 in_FrontWidthMax: 700,
 in_WeightMax: 12,
 in_FingergripTypeTop: "Wood",
 in_FingergripTypeBtm: "Wood",
 in_HandleDesign: "All",
 in_HandlePosType: "All",
 Descriptor: "140mm_1_1_140mm",
 TableSequence: 452
}
,{
 _id: 1428,
 in_TypeElement: "All",
 in_FrontDesign: "WoodFrame",
 in_AdditionalInfo1: "All",
 in_AdditionalInfo2: "All",
 in_AdditionalInfo3: "WidthCoveredHeight",
 in_FrameWidthMin: 0,
 in_FrameWidthMax: 100,
 in_FrontHeightMin: 1500,
 in_FrontHeightMax: 2100,
 in_FrontWidthMin: 0,
 in_FrontWidthMax: 700,
 in_WeightMax: 17,
 in_FingergripTypeTop: "Wood",
 in_FingergripTypeBtm: "Wood",
 in_HandleDesign: "All",
 in_HandlePosType: "All",
 Descriptor: "140mm_1_1_1_140mm",
 TableSequence: 453
}
,{
 _id: 1429,
 in_TypeElement: "All",
 in_FrontDesign: "WoodFrame",
 in_AdditionalInfo1: "All",
 in_AdditionalInfo2: "All",
 in_AdditionalInfo3: "WidthCoveredHeight",
 in_FrameWidthMin: 0,
 in_FrameWidthMax: 100,
 in_FrontHeightMin: 2100,
 in_FrontHeightMax: 2500,
 in_FrontWidthMin: 0,
 in_FrontWidthMax: 700,
 in_WeightMax: 22,
 in_FingergripTypeTop: "Wood",
 in_FingergripTypeBtm: "Wood",
 in_HandleDesign: "All",
 in_HandlePosType: "All",
 Descriptor: "140mm_1_1_1_1_140mm",
 TableSequence: 454
}
,{
 _id: 1430,
 in_TypeElement: "All",
 in_FrontDesign: "WoodFrame",
 in_AdditionalInfo1: "All",
 in_AdditionalInfo2: "All",
 in_AdditionalInfo3: "WidthCoveredHeight",
 in_FrameWidthMin: 0,
 in_FrameWidthMax: 100,
 in_FrontHeightMin: 2500,
 in_FrontHeightMax: 3000,
 in_FrontWidthMin: 0,
 in_FrontWidthMax: 700,
 in_WeightMax: 28,
 in_FingergripTypeTop: "Wood",
 in_FingergripTypeBtm: "Wood",
 in_HandleDesign: "All",
 in_HandlePosType: "All",
 Descriptor: "140mm_1_1_1_1_1_140mm",
 TableSequence: 455
}
,{
 _id: 1431,
 in_TypeElement: "All",
 in_FrontDesign: "WoodFrame",
 in_AdditionalInfo1: "All",
 in_AdditionalInfo2: "All",
 in_AdditionalInfo3: "WidthCoveredHeight",
 in_FrameWidthMin: 0,
 in_FrameWidthMax: 100,
 in_FrontHeightMin: 0,
 in_FrontHeightMax: 750,
 in_FrontWidthMin: 0,
 in_FrontWidthMax: 700,
 in_WeightMax: 6,
 in_FingergripTypeTop: "NoFingergrip",
 in_FingergripTypeBtm: "Wood",
 in_HandleDesign: "All",
 in_HandlePosType: "All",
 Descriptor: "140mm_1_140mm",
 TableSequence: 461
}
,{
 _id: 1432,
 in_TypeElement: "All",
 in_FrontDesign: "WoodFrame",
 in_AdditionalInfo1: "All",
 in_AdditionalInfo2: "All",
 in_AdditionalInfo3: "WidthCoveredHeight",
 in_FrameWidthMin: 0,
 in_FrameWidthMax: 100,
 in_FrontHeightMin: 750,
 in_FrontHeightMax: 1500,
 in_FrontWidthMin: 0,
 in_FrontWidthMax: 700,
 in_WeightMax: 12,
 in_FingergripTypeTop: "NoFingergrip",
 in_FingergripTypeBtm: "Wood",
 in_HandleDesign: "All",
 in_HandlePosType: "All",
 Descriptor: "140mm_1_1_140mm",
 TableSequence: 462
}
,{
 _id: 1433,
 in_TypeElement: "All",
 in_FrontDesign: "WoodFrame",
 in_AdditionalInfo1: "All",
 in_AdditionalInfo2: "All",
 in_AdditionalInfo3: "WidthCoveredHeight",
 in_FrameWidthMin: 0,
 in_FrameWidthMax: 100,
 in_FrontHeightMin: 1500,
 in_FrontHeightMax: 2100,
 in_FrontWidthMin: 0,
 in_FrontWidthMax: 700,
 in_WeightMax: 17,
 in_FingergripTypeTop: "NoFingergrip",
 in_FingergripTypeBtm: "Wood",
 in_HandleDesign: "All",
 in_HandlePosType: "All",
 Descriptor: "140mm_1_1_1_140mm",
 TableSequence: 463
}
,{
 _id: 1434,
 in_TypeElement: "All",
 in_FrontDesign: "WoodFrame",
 in_AdditionalInfo1: "All",
 in_AdditionalInfo2: "All",
 in_AdditionalInfo3: "WidthCoveredHeight",
 in_FrameWidthMin: 0,
 in_FrameWidthMax: 100,
 in_FrontHeightMin: 2100,
 in_FrontHeightMax: 2500,
 in_FrontWidthMin: 0,
 in_FrontWidthMax: 700,
 in_WeightMax: 22,
 in_FingergripTypeTop: "NoFingergrip",
 in_FingergripTypeBtm: "Wood",
 in_HandleDesign: "All",
 in_HandlePosType: "All",
 Descriptor: "140mm_1_1_1_1_140mm",
 TableSequence: 464
}
,{
 _id: 1435,
 in_TypeElement: "All",
 in_FrontDesign: "WoodFrame",
 in_AdditionalInfo1: "All",
 in_AdditionalInfo2: "All",
 in_AdditionalInfo3: "WidthCoveredHeight",
 in_FrameWidthMin: 0,
 in_FrameWidthMax: 100,
 in_FrontHeightMin: 2500,
 in_FrontHeightMax: 3000,
 in_FrontWidthMin: 0,
 in_FrontWidthMax: 700,
 in_WeightMax: 28,
 in_FingergripTypeTop: "NoFingergrip",
 in_FingergripTypeBtm: "Wood",
 in_HandleDesign: "All",
 in_HandlePosType: "All",
 Descriptor: "140mm_1_1_1_1_1_140mm",
 TableSequence: 465
}
,{
 _id: 1436,
 in_TypeElement: "All",
 in_FrontDesign: "WoodFrame",
 in_AdditionalInfo1: "All",
 in_AdditionalInfo2: "All",
 in_AdditionalInfo3: "WidthCoveredHeight",
 in_FrameWidthMin: 0,
 in_FrameWidthMax: 100,
 in_FrontHeightMin: 0,
 in_FrontHeightMax: 750,
 in_FrontWidthMin: 0,
 in_FrontWidthMax: 700,
 in_WeightMax: 6,
 in_FingergripTypeTop: "NoFingergrip",
 in_FingergripTypeBtm: "NoFingergrip",
 in_HandleDesign: "50",
 in_HandlePosType: "StripeBtm",
 Descriptor: "140mm_1_140mm",
 TableSequence: 471
}
,{
 _id: 1437,
 in_TypeElement: "All",
 in_FrontDesign: "WoodFrame",
 in_AdditionalInfo1: "All",
 in_AdditionalInfo2: "All",
 in_AdditionalInfo3: "WidthCoveredHeight",
 in_FrameWidthMin: 0,
 in_FrameWidthMax: 100,
 in_FrontHeightMin: 750,
 in_FrontHeightMax: 1500,
 in_FrontWidthMin: 0,
 in_FrontWidthMax: 700,
 in_WeightMax: 12,
 in_FingergripTypeTop: "NoFingergrip",
 in_FingergripTypeBtm: "NoFingergrip",
 in_HandleDesign: "50",
 in_HandlePosType: "StripeBtm",
 Descriptor: "140mm_1_1_140mm",
 TableSequence: 472
}
,{
 _id: 1438,
 in_TypeElement: "All",
 in_FrontDesign: "WoodFrame",
 in_AdditionalInfo1: "All",
 in_AdditionalInfo2: "All",
 in_AdditionalInfo3: "WidthCoveredHeight",
 in_FrameWidthMin: 0,
 in_FrameWidthMax: 100,
 in_FrontHeightMin: 1500,
 in_FrontHeightMax: 2100,
 in_FrontWidthMin: 0,
 in_FrontWidthMax: 700,
 in_WeightMax: 17,
 in_FingergripTypeTop: "NoFingergrip",
 in_FingergripTypeBtm: "NoFingergrip",
 in_HandleDesign: "50",
 in_HandlePosType: "StripeBtm",
 Descriptor: "140mm_1_1_1_140mm",
 TableSequence: 473
}
,{
 _id: 1439,
 in_TypeElement: "All",
 in_FrontDesign: "WoodFrame",
 in_AdditionalInfo1: "All",
 in_AdditionalInfo2: "All",
 in_AdditionalInfo3: "WidthCoveredHeight",
 in_FrameWidthMin: 0,
 in_FrameWidthMax: 100,
 in_FrontHeightMin: 2100,
 in_FrontHeightMax: 2500,
 in_FrontWidthMin: 0,
 in_FrontWidthMax: 700,
 in_WeightMax: 22,
 in_FingergripTypeTop: "NoFingergrip",
 in_FingergripTypeBtm: "NoFingergrip",
 in_HandleDesign: "50",
 in_HandlePosType: "StripeBtm",
 Descriptor: "140mm_1_1_1_1_140mm",
 TableSequence: 474
}
,{
 _id: 1440,
 in_TypeElement: "All",
 in_FrontDesign: "WoodFrame",
 in_AdditionalInfo1: "All",
 in_AdditionalInfo2: "All",
 in_AdditionalInfo3: "WidthCoveredHeight",
 in_FrameWidthMin: 0,
 in_FrameWidthMax: 100,
 in_FrontHeightMin: 2500,
 in_FrontHeightMax: 3000,
 in_FrontWidthMin: 0,
 in_FrontWidthMax: 700,
 in_WeightMax: 28,
 in_FingergripTypeTop: "NoFingergrip",
 in_FingergripTypeBtm: "NoFingergrip",
 in_HandleDesign: "50",
 in_HandlePosType: "StripeBtm",
 Descriptor: "140mm_1_1_1_1_1_140mm",
 TableSequence: 475
}
,{
 _id: 1441,
 in_TypeElement: "All",
 in_FrontDesign: "WoodFrame",
 in_AdditionalInfo1: "All",
 in_AdditionalInfo2: "All",
 in_AdditionalInfo3: "WidthCoveredHeight",
 in_FrameWidthMin: 0,
 in_FrameWidthMax: 100,
 in_FrontHeightMin: 0,
 in_FrontHeightMax: 750,
 in_FrontWidthMin: 0,
 in_FrontWidthMax: 700,
 in_WeightMax: 6,
 in_FingergripTypeTop: "NoFingergrip",
 in_FingergripTypeBtm: "NoFingergrip",
 in_HandleDesign: "50",
 in_HandlePosType: "StripeTop",
 Descriptor: "140mm_1_140mm",
 TableSequence: 481
}
,{
 _id: 1442,
 in_TypeElement: "All",
 in_FrontDesign: "WoodFrame",
 in_AdditionalInfo1: "All",
 in_AdditionalInfo2: "All",
 in_AdditionalInfo3: "WidthCoveredHeight",
 in_FrameWidthMin: 0,
 in_FrameWidthMax: 100,
 in_FrontHeightMin: 750,
 in_FrontHeightMax: 1500,
 in_FrontWidthMin: 0,
 in_FrontWidthMax: 700,
 in_WeightMax: 12,
 in_FingergripTypeTop: "NoFingergrip",
 in_FingergripTypeBtm: "NoFingergrip",
 in_HandleDesign: "50",
 in_HandlePosType: "StripeTop",
 Descriptor: "140mm_1_1_140mm",
 TableSequence: 482
}
,{
 _id: 1443,
 in_TypeElement: "All",
 in_FrontDesign: "WoodFrame",
 in_AdditionalInfo1: "All",
 in_AdditionalInfo2: "All",
 in_AdditionalInfo3: "WidthCoveredHeight",
 in_FrameWidthMin: 0,
 in_FrameWidthMax: 100,
 in_FrontHeightMin: 1500,
 in_FrontHeightMax: 2100,
 in_FrontWidthMin: 0,
 in_FrontWidthMax: 700,
 in_WeightMax: 17,
 in_FingergripTypeTop: "NoFingergrip",
 in_FingergripTypeBtm: "NoFingergrip",
 in_HandleDesign: "50",
 in_HandlePosType: "StripeTop",
 Descriptor: "140mm_1_1_1_140mm",
 TableSequence: 483
}
,{
 _id: 1444,
 in_TypeElement: "All",
 in_FrontDesign: "WoodFrame",
 in_AdditionalInfo1: "All",
 in_AdditionalInfo2: "All",
 in_AdditionalInfo3: "WidthCoveredHeight",
 in_FrameWidthMin: 0,
 in_FrameWidthMax: 100,
 in_FrontHeightMin: 2100,
 in_FrontHeightMax: 2500,
 in_FrontWidthMin: 0,
 in_FrontWidthMax: 700,
 in_WeightMax: 22,
 in_FingergripTypeTop: "NoFingergrip",
 in_FingergripTypeBtm: "NoFingergrip",
 in_HandleDesign: "50",
 in_HandlePosType: "StripeTop",
 Descriptor: "140mm_1_1_1_1_140mm",
 TableSequence: 484
}
,{
 _id: 1445,
 in_TypeElement: "All",
 in_FrontDesign: "WoodFrame",
 in_AdditionalInfo1: "All",
 in_AdditionalInfo2: "All",
 in_AdditionalInfo3: "WidthCoveredHeight",
 in_FrameWidthMin: 0,
 in_FrameWidthMax: 100,
 in_FrontHeightMin: 2500,
 in_FrontHeightMax: 3000,
 in_FrontWidthMin: 0,
 in_FrontWidthMax: 700,
 in_WeightMax: 28,
 in_FingergripTypeTop: "NoFingergrip",
 in_FingergripTypeBtm: "NoFingergrip",
 in_HandleDesign: "50",
 in_HandlePosType: "StripeTop",
 Descriptor: "140mm_1_1_1_1_1_140mm",
 TableSequence: 485
}
,{
 _id: 1446,
 in_TypeElement: "All",
 in_FrontDesign: "WoodFrame",
 in_AdditionalInfo1: "All",
 in_AdditionalInfo2: "All",
 in_AdditionalInfo3: "WidthCoveredHeight",
 in_FrameWidthMin: 100,
 in_FrameWidthMax: 120,
 in_FrontHeightMin: 0,
 in_FrontHeightMax: 750,
 in_FrontWidthMin: 0,
 in_FrontWidthMax: 700,
 in_WeightMax: 6,
 in_FingergripTypeTop: "NoFingergrip",
 in_FingergripTypeBtm: "NoFingergrip",
 in_HandleDesign: "All",
 in_HandlePosType: "All",
 Descriptor: "60mm_1_60mm",
 TableSequence: 501
}
,{
 _id: 1447,
 in_TypeElement: "All",
 in_FrontDesign: "WoodFrame",
 in_AdditionalInfo1: "All",
 in_AdditionalInfo2: "All",
 in_AdditionalInfo3: "WidthCoveredHeight",
 in_FrameWidthMin: 100,
 in_FrameWidthMax: 120,
 in_FrontHeightMin: 750,
 in_FrontHeightMax: 1500,
 in_FrontWidthMin: 0,
 in_FrontWidthMax: 700,
 in_WeightMax: 12,
 in_FingergripTypeTop: "NoFingergrip",
 in_FingergripTypeBtm: "NoFingergrip",
 in_HandleDesign: "All",
 in_HandlePosType: "All",
 Descriptor: "60mm_1_1_60mm",
 TableSequence: 502
}
,{
 _id: 1448,
 in_TypeElement: "All",
 in_FrontDesign: "WoodFrame",
 in_AdditionalInfo1: "All",
 in_AdditionalInfo2: "All",
 in_AdditionalInfo3: "WidthCoveredHeight",
 in_FrameWidthMin: 100,
 in_FrameWidthMax: 120,
 in_FrontHeightMin: 1500,
 in_FrontHeightMax: 2100,
 in_FrontWidthMin: 0,
 in_FrontWidthMax: 700,
 in_WeightMax: 17,
 in_FingergripTypeTop: "NoFingergrip",
 in_FingergripTypeBtm: "NoFingergrip",
 in_HandleDesign: "All",
 in_HandlePosType: "All",
 Descriptor: "60mm_1_1_1_60mm",
 TableSequence: 503
}
,{
 _id: 1449,
 in_TypeElement: "All",
 in_FrontDesign: "WoodFrame",
 in_AdditionalInfo1: "All",
 in_AdditionalInfo2: "All",
 in_AdditionalInfo3: "WidthCoveredHeight",
 in_FrameWidthMin: 100,
 in_FrameWidthMax: 120,
 in_FrontHeightMin: 2100,
 in_FrontHeightMax: 2500,
 in_FrontWidthMin: 0,
 in_FrontWidthMax: 700,
 in_WeightMax: 22,
 in_FingergripTypeTop: "NoFingergrip",
 in_FingergripTypeBtm: "NoFingergrip",
 in_HandleDesign: "All",
 in_HandlePosType: "All",
 Descriptor: "60mm_1_1_1_1_60mm",
 TableSequence: 504
}
,{
 _id: 1450,
 in_TypeElement: "All",
 in_FrontDesign: "WoodFrame",
 in_AdditionalInfo1: "All",
 in_AdditionalInfo2: "All",
 in_AdditionalInfo3: "WidthCoveredHeight",
 in_FrameWidthMin: 100,
 in_FrameWidthMax: 120,
 in_FrontHeightMin: 2500,
 in_FrontHeightMax: 3000,
 in_FrontWidthMin: 0,
 in_FrontWidthMax: 700,
 in_WeightMax: 28,
 in_FingergripTypeTop: "NoFingergrip",
 in_FingergripTypeBtm: "NoFingergrip",
 in_HandleDesign: "All",
 in_HandlePosType: "All",
 Descriptor: "60mm_1_1_1_1_1_60mm",
 TableSequence: 505
}
,{
 _id: 1451,
 in_TypeElement: "All",
 in_FrontDesign: "WoodFrame",
 in_AdditionalInfo1: "All",
 in_AdditionalInfo2: "All",
 in_AdditionalInfo3: "WidthCoveredHeight",
 in_FrameWidthMin: 100,
 in_FrameWidthMax: 120,
 in_FrontHeightMin: 0,
 in_FrontHeightMax: 750,
 in_FrontWidthMin: 0,
 in_FrontWidthMax: 700,
 in_WeightMax: 6,
 in_FingergripTypeTop: "Metal",
 in_FingergripTypeBtm: "NoFingergrip",
 in_HandleDesign: "All",
 in_HandlePosType: "All",
 Descriptor: "60mm_1_60mm",
 TableSequence: 510
}
,{
 _id: 1452,
 in_TypeElement: "All",
 in_FrontDesign: "WoodFrame",
 in_AdditionalInfo1: "All",
 in_AdditionalInfo2: "All",
 in_AdditionalInfo3: "WidthCoveredHeight",
 in_FrameWidthMin: 100,
 in_FrameWidthMax: 120,
 in_FrontHeightMin: 750,
 in_FrontHeightMax: 1500,
 in_FrontWidthMin: 0,
 in_FrontWidthMax: 700,
 in_WeightMax: 12,
 in_FingergripTypeTop: "Metal",
 in_FingergripTypeBtm: "NoFingergrip",
 in_HandleDesign: "All",
 in_HandlePosType: "All",
 Descriptor: "60mm_1_1_60mm",
 TableSequence: 511
}
,{
 _id: 1453,
 in_TypeElement: "All",
 in_FrontDesign: "WoodFrame",
 in_AdditionalInfo1: "All",
 in_AdditionalInfo2: "All",
 in_AdditionalInfo3: "WidthCoveredHeight",
 in_FrameWidthMin: 100,
 in_FrameWidthMax: 120,
 in_FrontHeightMin: 1500,
 in_FrontHeightMax: 2100,
 in_FrontWidthMin: 0,
 in_FrontWidthMax: 700,
 in_WeightMax: 17,
 in_FingergripTypeTop: "Metal",
 in_FingergripTypeBtm: "NoFingergrip",
 in_HandleDesign: "All",
 in_HandlePosType: "All",
 Descriptor: "60mm_1_1_1_60mm",
 TableSequence: 512
}
,{
 _id: 1454,
 in_TypeElement: "All",
 in_FrontDesign: "WoodFrame",
 in_AdditionalInfo1: "All",
 in_AdditionalInfo2: "All",
 in_AdditionalInfo3: "WidthCoveredHeight",
 in_FrameWidthMin: 100,
 in_FrameWidthMax: 120,
 in_FrontHeightMin: 2100,
 in_FrontHeightMax: 2500,
 in_FrontWidthMin: 0,
 in_FrontWidthMax: 700,
 in_WeightMax: 22,
 in_FingergripTypeTop: "Metal",
 in_FingergripTypeBtm: "NoFingergrip",
 in_HandleDesign: "All",
 in_HandlePosType: "All",
 Descriptor: "60mm_1_1_1_1_60mm",
 TableSequence: 513
}
,{
 _id: 1455,
 in_TypeElement: "All",
 in_FrontDesign: "WoodFrame",
 in_AdditionalInfo1: "All",
 in_AdditionalInfo2: "All",
 in_AdditionalInfo3: "WidthCoveredHeight",
 in_FrameWidthMin: 100,
 in_FrameWidthMax: 120,
 in_FrontHeightMin: 2500,
 in_FrontHeightMax: 3000,
 in_FrontWidthMin: 0,
 in_FrontWidthMax: 700,
 in_WeightMax: 28,
 in_FingergripTypeTop: "Metal",
 in_FingergripTypeBtm: "NoFingergrip",
 in_HandleDesign: "All",
 in_HandlePosType: "All",
 Descriptor: "60mm_1_1_1_1_1_60mm",
 TableSequence: 514
}
,{
 _id: 1456,
 in_TypeElement: "All",
 in_FrontDesign: "WoodFrame",
 in_AdditionalInfo1: "All",
 in_AdditionalInfo2: "All",
 in_AdditionalInfo3: "WidthCoveredHeight",
 in_FrameWidthMin: 100,
 in_FrameWidthMax: 120,
 in_FrontHeightMin: 0,
 in_FrontHeightMax: 750,
 in_FrontWidthMin: 0,
 in_FrontWidthMax: 700,
 in_WeightMax: 6,
 in_FingergripTypeTop: "Wood",
 in_FingergripTypeBtm: "NoFingergrip",
 in_HandleDesign: "All",
 in_HandlePosType: "All",
 Descriptor: "60mm_1_60mm",
 TableSequence: 521
}
,{
 _id: 1457,
 in_TypeElement: "All",
 in_FrontDesign: "WoodFrame",
 in_AdditionalInfo1: "All",
 in_AdditionalInfo2: "All",
 in_AdditionalInfo3: "WidthCoveredHeight",
 in_FrameWidthMin: 100,
 in_FrameWidthMax: 120,
 in_FrontHeightMin: 750,
 in_FrontHeightMax: 1500,
 in_FrontWidthMin: 0,
 in_FrontWidthMax: 700,
 in_WeightMax: 12,
 in_FingergripTypeTop: "Wood",
 in_FingergripTypeBtm: "NoFingergrip",
 in_HandleDesign: "All",
 in_HandlePosType: "All",
 Descriptor: "60mm_1_1_60mm",
 TableSequence: 522
}
,{
 _id: 1458,
 in_TypeElement: "All",
 in_FrontDesign: "WoodFrame",
 in_AdditionalInfo1: "All",
 in_AdditionalInfo2: "All",
 in_AdditionalInfo3: "WidthCoveredHeight",
 in_FrameWidthMin: 100,
 in_FrameWidthMax: 120,
 in_FrontHeightMin: 1500,
 in_FrontHeightMax: 2100,
 in_FrontWidthMin: 0,
 in_FrontWidthMax: 700,
 in_WeightMax: 17,
 in_FingergripTypeTop: "Wood",
 in_FingergripTypeBtm: "NoFingergrip",
 in_HandleDesign: "All",
 in_HandlePosType: "All",
 Descriptor: "60mm_1_1_1_60mm",
 TableSequence: 523
}
,{
 _id: 1459,
 in_TypeElement: "All",
 in_FrontDesign: "WoodFrame",
 in_AdditionalInfo1: "All",
 in_AdditionalInfo2: "All",
 in_AdditionalInfo3: "WidthCoveredHeight",
 in_FrameWidthMin: 100,
 in_FrameWidthMax: 120,
 in_FrontHeightMin: 2100,
 in_FrontHeightMax: 2500,
 in_FrontWidthMin: 0,
 in_FrontWidthMax: 700,
 in_WeightMax: 22,
 in_FingergripTypeTop: "Wood",
 in_FingergripTypeBtm: "NoFingergrip",
 in_HandleDesign: "All",
 in_HandlePosType: "All",
 Descriptor: "60mm_1_1_1_1_60mm",
 TableSequence: 524
}
,{
 _id: 1460,
 in_TypeElement: "All",
 in_FrontDesign: "WoodFrame",
 in_AdditionalInfo1: "All",
 in_AdditionalInfo2: "All",
 in_AdditionalInfo3: "WidthCoveredHeight",
 in_FrameWidthMin: 100,
 in_FrameWidthMax: 120,
 in_FrontHeightMin: 2500,
 in_FrontHeightMax: 3000,
 in_FrontWidthMin: 0,
 in_FrontWidthMax: 700,
 in_WeightMax: 28,
 in_FingergripTypeTop: "Wood",
 in_FingergripTypeBtm: "NoFingergrip",
 in_HandleDesign: "All",
 in_HandlePosType: "All",
 Descriptor: "60mm_1_1_1_1_1_60mm",
 TableSequence: 525
}
,{
 _id: 1461,
 in_TypeElement: "All",
 in_FrontDesign: "WoodFrame",
 in_AdditionalInfo1: "All",
 in_AdditionalInfo2: "All",
 in_AdditionalInfo3: "WidthCoveredHeight",
 in_FrameWidthMin: 100,
 in_FrameWidthMax: 120,
 in_FrontHeightMin: 0,
 in_FrontHeightMax: 750,
 in_FrontWidthMin: 0,
 in_FrontWidthMax: 700,
 in_WeightMax: 6,
 in_FingergripTypeTop: "Metal",
 in_FingergripTypeBtm: "Metal",
 in_HandleDesign: "All",
 in_HandlePosType: "All",
 Descriptor: "60mm_1_60mm",
 TableSequence: 531
}
,{
 _id: 1462,
 in_TypeElement: "All",
 in_FrontDesign: "WoodFrame",
 in_AdditionalInfo1: "All",
 in_AdditionalInfo2: "All",
 in_AdditionalInfo3: "WidthCoveredHeight",
 in_FrameWidthMin: 100,
 in_FrameWidthMax: 120,
 in_FrontHeightMin: 750,
 in_FrontHeightMax: 1500,
 in_FrontWidthMin: 0,
 in_FrontWidthMax: 700,
 in_WeightMax: 12,
 in_FingergripTypeTop: "Metal",
 in_FingergripTypeBtm: "Metal",
 in_HandleDesign: "All",
 in_HandlePosType: "All",
 Descriptor: "60mm_1_1_60mm",
 TableSequence: 532
}
,{
 _id: 1463,
 in_TypeElement: "All",
 in_FrontDesign: "WoodFrame",
 in_AdditionalInfo1: "All",
 in_AdditionalInfo2: "All",
 in_AdditionalInfo3: "WidthCoveredHeight",
 in_FrameWidthMin: 100,
 in_FrameWidthMax: 120,
 in_FrontHeightMin: 1500,
 in_FrontHeightMax: 2100,
 in_FrontWidthMin: 0,
 in_FrontWidthMax: 700,
 in_WeightMax: 17,
 in_FingergripTypeTop: "Metal",
 in_FingergripTypeBtm: "Metal",
 in_HandleDesign: "All",
 in_HandlePosType: "All",
 Descriptor: "60mm_1_1_1_60mm",
 TableSequence: 533
}
,{
 _id: 1464,
 in_TypeElement: "All",
 in_FrontDesign: "WoodFrame",
 in_AdditionalInfo1: "All",
 in_AdditionalInfo2: "All",
 in_AdditionalInfo3: "WidthCoveredHeight",
 in_FrameWidthMin: 100,
 in_FrameWidthMax: 120,
 in_FrontHeightMin: 2100,
 in_FrontHeightMax: 2500,
 in_FrontWidthMin: 0,
 in_FrontWidthMax: 700,
 in_WeightMax: 22,
 in_FingergripTypeTop: "Metal",
 in_FingergripTypeBtm: "Metal",
 in_HandleDesign: "All",
 in_HandlePosType: "All",
 Descriptor: "60mm_1_1_1_1_60mm",
 TableSequence: 534
}
,{
 _id: 1465,
 in_TypeElement: "All",
 in_FrontDesign: "WoodFrame",
 in_AdditionalInfo1: "All",
 in_AdditionalInfo2: "All",
 in_AdditionalInfo3: "WidthCoveredHeight",
 in_FrameWidthMin: 100,
 in_FrameWidthMax: 120,
 in_FrontHeightMin: 2500,
 in_FrontHeightMax: 3000,
 in_FrontWidthMin: 0,
 in_FrontWidthMax: 700,
 in_WeightMax: 28,
 in_FingergripTypeTop: "Metal",
 in_FingergripTypeBtm: "Metal",
 in_HandleDesign: "All",
 in_HandlePosType: "All",
 Descriptor: "60mm_1_1_1_1_1_60mm",
 TableSequence: 535
}
,{
 _id: 1466,
 in_TypeElement: "All",
 in_FrontDesign: "WoodFrame",
 in_AdditionalInfo1: "All",
 in_AdditionalInfo2: "All",
 in_AdditionalInfo3: "WidthCoveredHeight",
 in_FrameWidthMin: 100,
 in_FrameWidthMax: 120,
 in_FrontHeightMin: 0,
 in_FrontHeightMax: 750,
 in_FrontWidthMin: 0,
 in_FrontWidthMax: 700,
 in_WeightMax: 6,
 in_FingergripTypeTop: "NoFingergrip",
 in_FingergripTypeBtm: "Metal",
 in_HandleDesign: "All",
 in_HandlePosType: "All",
 Descriptor: "60mm_1_60mm",
 TableSequence: 541
}
,{
 _id: 1467,
 in_TypeElement: "All",
 in_FrontDesign: "WoodFrame",
 in_AdditionalInfo1: "All",
 in_AdditionalInfo2: "All",
 in_AdditionalInfo3: "WidthCoveredHeight",
 in_FrameWidthMin: 100,
 in_FrameWidthMax: 120,
 in_FrontHeightMin: 750,
 in_FrontHeightMax: 1500,
 in_FrontWidthMin: 0,
 in_FrontWidthMax: 700,
 in_WeightMax: 12,
 in_FingergripTypeTop: "NoFingergrip",
 in_FingergripTypeBtm: "Metal",
 in_HandleDesign: "All",
 in_HandlePosType: "All",
 Descriptor: "60mm_1_1_60mm",
 TableSequence: 542
}
,{
 _id: 1468,
 in_TypeElement: "All",
 in_FrontDesign: "WoodFrame",
 in_AdditionalInfo1: "All",
 in_AdditionalInfo2: "All",
 in_AdditionalInfo3: "WidthCoveredHeight",
 in_FrameWidthMin: 100,
 in_FrameWidthMax: 120,
 in_FrontHeightMin: 1500,
 in_FrontHeightMax: 2100,
 in_FrontWidthMin: 0,
 in_FrontWidthMax: 700,
 in_WeightMax: 17,
 in_FingergripTypeTop: "NoFingergrip",
 in_FingergripTypeBtm: "Metal",
 in_HandleDesign: "All",
 in_HandlePosType: "All",
 Descriptor: "60mm_1_1_1_60mm",
 TableSequence: 543
}
,{
 _id: 1469,
 in_TypeElement: "All",
 in_FrontDesign: "WoodFrame",
 in_AdditionalInfo1: "All",
 in_AdditionalInfo2: "All",
 in_AdditionalInfo3: "WidthCoveredHeight",
 in_FrameWidthMin: 100,
 in_FrameWidthMax: 120,
 in_FrontHeightMin: 2100,
 in_FrontHeightMax: 2500,
 in_FrontWidthMin: 0,
 in_FrontWidthMax: 700,
 in_WeightMax: 22,
 in_FingergripTypeTop: "NoFingergrip",
 in_FingergripTypeBtm: "Metal",
 in_HandleDesign: "All",
 in_HandlePosType: "All",
 Descriptor: "60mm_1_1_1_1_60mm",
 TableSequence: 544
}
,{
 _id: 1470,
 in_TypeElement: "All",
 in_FrontDesign: "WoodFrame",
 in_AdditionalInfo1: "All",
 in_AdditionalInfo2: "All",
 in_AdditionalInfo3: "WidthCoveredHeight",
 in_FrameWidthMin: 100,
 in_FrameWidthMax: 120,
 in_FrontHeightMin: 2500,
 in_FrontHeightMax: 3000,
 in_FrontWidthMin: 0,
 in_FrontWidthMax: 700,
 in_WeightMax: 28,
 in_FingergripTypeTop: "NoFingergrip",
 in_FingergripTypeBtm: "Metal",
 in_HandleDesign: "All",
 in_HandlePosType: "All",
 Descriptor: "60mm_1_1_1_1_1_60mm",
 TableSequence: 545
}
,{
 _id: 1471,
 in_TypeElement: "All",
 in_FrontDesign: "WoodFrame",
 in_AdditionalInfo1: "All",
 in_AdditionalInfo2: "All",
 in_AdditionalInfo3: "WidthCoveredHeight",
 in_FrameWidthMin: 100,
 in_FrameWidthMax: 120,
 in_FrontHeightMin: 0,
 in_FrontHeightMax: 750,
 in_FrontWidthMin: 0,
 in_FrontWidthMax: 700,
 in_WeightMax: 6,
 in_FingergripTypeTop: "Wood",
 in_FingergripTypeBtm: "Wood",
 in_HandleDesign: "All",
 in_HandlePosType: "All",
 Descriptor: "60mm_1_60mm",
 TableSequence: 551
}
,{
 _id: 1472,
 in_TypeElement: "All",
 in_FrontDesign: "WoodFrame",
 in_AdditionalInfo1: "All",
 in_AdditionalInfo2: "All",
 in_AdditionalInfo3: "WidthCoveredHeight",
 in_FrameWidthMin: 100,
 in_FrameWidthMax: 120,
 in_FrontHeightMin: 750,
 in_FrontHeightMax: 1500,
 in_FrontWidthMin: 0,
 in_FrontWidthMax: 700,
 in_WeightMax: 12,
 in_FingergripTypeTop: "Wood",
 in_FingergripTypeBtm: "Wood",
 in_HandleDesign: "All",
 in_HandlePosType: "All",
 Descriptor: "60mm_1_1_60mm",
 TableSequence: 552
}
,{
 _id: 1473,
 in_TypeElement: "All",
 in_FrontDesign: "WoodFrame",
 in_AdditionalInfo1: "All",
 in_AdditionalInfo2: "All",
 in_AdditionalInfo3: "WidthCoveredHeight",
 in_FrameWidthMin: 100,
 in_FrameWidthMax: 120,
 in_FrontHeightMin: 1500,
 in_FrontHeightMax: 2100,
 in_FrontWidthMin: 0,
 in_FrontWidthMax: 700,
 in_WeightMax: 17,
 in_FingergripTypeTop: "Wood",
 in_FingergripTypeBtm: "Wood",
 in_HandleDesign: "All",
 in_HandlePosType: "All",
 Descriptor: "60mm_1_1_1_60mm",
 TableSequence: 553
}
,{
 _id: 1474,
 in_TypeElement: "All",
 in_FrontDesign: "WoodFrame",
 in_AdditionalInfo1: "All",
 in_AdditionalInfo2: "All",
 in_AdditionalInfo3: "WidthCoveredHeight",
 in_FrameWidthMin: 100,
 in_FrameWidthMax: 120,
 in_FrontHeightMin: 2100,
 in_FrontHeightMax: 2500,
 in_FrontWidthMin: 0,
 in_FrontWidthMax: 700,
 in_WeightMax: 22,
 in_FingergripTypeTop: "Wood",
 in_FingergripTypeBtm: "Wood",
 in_HandleDesign: "All",
 in_HandlePosType: "All",
 Descriptor: "60mm_1_1_1_1_60mm",
 TableSequence: 554
}
,{
 _id: 1475,
 in_TypeElement: "All",
 in_FrontDesign: "WoodFrame",
 in_AdditionalInfo1: "All",
 in_AdditionalInfo2: "All",
 in_AdditionalInfo3: "WidthCoveredHeight",
 in_FrameWidthMin: 100,
 in_FrameWidthMax: 120,
 in_FrontHeightMin: 2500,
 in_FrontHeightMax: 3000,
 in_FrontWidthMin: 0,
 in_FrontWidthMax: 700,
 in_WeightMax: 28,
 in_FingergripTypeTop: "Wood",
 in_FingergripTypeBtm: "Wood",
 in_HandleDesign: "All",
 in_HandlePosType: "All",
 Descriptor: "60mm_1_1_1_1_1_60mm",
 TableSequence: 555
}
,{
 _id: 1476,
 in_TypeElement: "All",
 in_FrontDesign: "WoodFrame",
 in_AdditionalInfo1: "All",
 in_AdditionalInfo2: "All",
 in_AdditionalInfo3: "WidthCoveredHeight",
 in_FrameWidthMin: 100,
 in_FrameWidthMax: 120,
 in_FrontHeightMin: 0,
 in_FrontHeightMax: 750,
 in_FrontWidthMin: 0,
 in_FrontWidthMax: 700,
 in_WeightMax: 6,
 in_FingergripTypeTop: "NoFingergrip",
 in_FingergripTypeBtm: "Wood",
 in_HandleDesign: "All",
 in_HandlePosType: "All",
 Descriptor: "60mm_1_60mm",
 TableSequence: 561
}
,{
 _id: 1477,
 in_TypeElement: "All",
 in_FrontDesign: "WoodFrame",
 in_AdditionalInfo1: "All",
 in_AdditionalInfo2: "All",
 in_AdditionalInfo3: "WidthCoveredHeight",
 in_FrameWidthMin: 100,
 in_FrameWidthMax: 120,
 in_FrontHeightMin: 750,
 in_FrontHeightMax: 1500,
 in_FrontWidthMin: 0,
 in_FrontWidthMax: 700,
 in_WeightMax: 12,
 in_FingergripTypeTop: "NoFingergrip",
 in_FingergripTypeBtm: "Wood",
 in_HandleDesign: "All",
 in_HandlePosType: "All",
 Descriptor: "60mm_1_1_60mm",
 TableSequence: 562
}
,{
 _id: 1478,
 in_TypeElement: "All",
 in_FrontDesign: "WoodFrame",
 in_AdditionalInfo1: "All",
 in_AdditionalInfo2: "All",
 in_AdditionalInfo3: "WidthCoveredHeight",
 in_FrameWidthMin: 100,
 in_FrameWidthMax: 120,
 in_FrontHeightMin: 1500,
 in_FrontHeightMax: 2100,
 in_FrontWidthMin: 0,
 in_FrontWidthMax: 700,
 in_WeightMax: 17,
 in_FingergripTypeTop: "NoFingergrip",
 in_FingergripTypeBtm: "Wood",
 in_HandleDesign: "All",
 in_HandlePosType: "All",
 Descriptor: "60mm_1_1_1_60mm",
 TableSequence: 563
}
,{
 _id: 1479,
 in_TypeElement: "All",
 in_FrontDesign: "WoodFrame",
 in_AdditionalInfo1: "All",
 in_AdditionalInfo2: "All",
 in_AdditionalInfo3: "WidthCoveredHeight",
 in_FrameWidthMin: 100,
 in_FrameWidthMax: 120,
 in_FrontHeightMin: 2100,
 in_FrontHeightMax: 2500,
 in_FrontWidthMin: 0,
 in_FrontWidthMax: 700,
 in_WeightMax: 22,
 in_FingergripTypeTop: "NoFingergrip",
 in_FingergripTypeBtm: "Wood",
 in_HandleDesign: "All",
 in_HandlePosType: "All",
 Descriptor: "60mm_1_1_1_1_60mm",
 TableSequence: 564
}
,{
 _id: 1480,
 in_TypeElement: "All",
 in_FrontDesign: "WoodFrame",
 in_AdditionalInfo1: "All",
 in_AdditionalInfo2: "All",
 in_AdditionalInfo3: "WidthCoveredHeight",
 in_FrameWidthMin: 100,
 in_FrameWidthMax: 120,
 in_FrontHeightMin: 2500,
 in_FrontHeightMax: 3000,
 in_FrontWidthMin: 0,
 in_FrontWidthMax: 700,
 in_WeightMax: 28,
 in_FingergripTypeTop: "NoFingergrip",
 in_FingergripTypeBtm: "Wood",
 in_HandleDesign: "All",
 in_HandlePosType: "All",
 Descriptor: "60mm_1_1_1_1_1_60mm",
 TableSequence: 565
}
,{
 _id: 1481,
 in_TypeElement: "All",
 in_FrontDesign: "WoodFrame",
 in_AdditionalInfo1: "All",
 in_AdditionalInfo2: "All",
 in_AdditionalInfo3: "WidthCoveredHeight",
 in_FrameWidthMin: 100,
 in_FrameWidthMax: 120,
 in_FrontHeightMin: 0,
 in_FrontHeightMax: 750,
 in_FrontWidthMin: 0,
 in_FrontWidthMax: 700,
 in_WeightMax: 6,
 in_FingergripTypeTop: "NoFingergrip",
 in_FingergripTypeBtm: "NoFingergrip",
 in_HandleDesign: "50",
 in_HandlePosType: "StripeBtm",
 Descriptor: "115mm_1_60mm",
 TableSequence: 571
}
,{
 _id: 1482,
 in_TypeElement: "All",
 in_FrontDesign: "WoodFrame",
 in_AdditionalInfo1: "All",
 in_AdditionalInfo2: "All",
 in_AdditionalInfo3: "WidthCoveredHeight",
 in_FrameWidthMin: 100,
 in_FrameWidthMax: 120,
 in_FrontHeightMin: 750,
 in_FrontHeightMax: 1500,
 in_FrontWidthMin: 0,
 in_FrontWidthMax: 700,
 in_WeightMax: 12,
 in_FingergripTypeTop: "NoFingergrip",
 in_FingergripTypeBtm: "NoFingergrip",
 in_HandleDesign: "50",
 in_HandlePosType: "StripeBtm",
 Descriptor: "115mm_1_1_60mm",
 TableSequence: 572
}
,{
 _id: 1483,
 in_TypeElement: "All",
 in_FrontDesign: "WoodFrame",
 in_AdditionalInfo1: "All",
 in_AdditionalInfo2: "All",
 in_AdditionalInfo3: "WidthCoveredHeight",
 in_FrameWidthMin: 100,
 in_FrameWidthMax: 120,
 in_FrontHeightMin: 1500,
 in_FrontHeightMax: 2100,
 in_FrontWidthMin: 0,
 in_FrontWidthMax: 700,
 in_WeightMax: 17,
 in_FingergripTypeTop: "NoFingergrip",
 in_FingergripTypeBtm: "NoFingergrip",
 in_HandleDesign: "50",
 in_HandlePosType: "StripeBtm",
 Descriptor: "115mm_1_1_1_60mm",
 TableSequence: 573
}
,{
 _id: 1484,
 in_TypeElement: "All",
 in_FrontDesign: "WoodFrame",
 in_AdditionalInfo1: "All",
 in_AdditionalInfo2: "All",
 in_AdditionalInfo3: "WidthCoveredHeight",
 in_FrameWidthMin: 100,
 in_FrameWidthMax: 120,
 in_FrontHeightMin: 2100,
 in_FrontHeightMax: 2500,
 in_FrontWidthMin: 0,
 in_FrontWidthMax: 700,
 in_WeightMax: 22,
 in_FingergripTypeTop: "NoFingergrip",
 in_FingergripTypeBtm: "NoFingergrip",
 in_HandleDesign: "50",
 in_HandlePosType: "StripeBtm",
 Descriptor: "115mm_1_1_1_1_60mm",
 TableSequence: 574
}
,{
 _id: 1485,
 in_TypeElement: "All",
 in_FrontDesign: "WoodFrame",
 in_AdditionalInfo1: "All",
 in_AdditionalInfo2: "All",
 in_AdditionalInfo3: "WidthCoveredHeight",
 in_FrameWidthMin: 100,
 in_FrameWidthMax: 120,
 in_FrontHeightMin: 2500,
 in_FrontHeightMax: 3000,
 in_FrontWidthMin: 0,
 in_FrontWidthMax: 700,
 in_WeightMax: 28,
 in_FingergripTypeTop: "NoFingergrip",
 in_FingergripTypeBtm: "NoFingergrip",
 in_HandleDesign: "50",
 in_HandlePosType: "StripeBtm",
 Descriptor: "115mm_1_1_1_1_1_60mm",
 TableSequence: 575
}
,{
 _id: 1486,
 in_TypeElement: "All",
 in_FrontDesign: "WoodFrame",
 in_AdditionalInfo1: "All",
 in_AdditionalInfo2: "All",
 in_AdditionalInfo3: "WidthCoveredHeight",
 in_FrameWidthMin: 100,
 in_FrameWidthMax: 120,
 in_FrontHeightMin: 0,
 in_FrontHeightMax: 750,
 in_FrontWidthMin: 0,
 in_FrontWidthMax: 700,
 in_WeightMax: 6,
 in_FingergripTypeTop: "NoFingergrip",
 in_FingergripTypeBtm: "NoFingergrip",
 in_HandleDesign: "50",
 in_HandlePosType: "StripeTop",
 Descriptor: "60mm_1_115mm",
 TableSequence: 581
}
,{
 _id: 1487,
 in_TypeElement: "All",
 in_FrontDesign: "WoodFrame",
 in_AdditionalInfo1: "All",
 in_AdditionalInfo2: "All",
 in_AdditionalInfo3: "WidthCoveredHeight",
 in_FrameWidthMin: 100,
 in_FrameWidthMax: 120,
 in_FrontHeightMin: 750,
 in_FrontHeightMax: 1500,
 in_FrontWidthMin: 0,
 in_FrontWidthMax: 700,
 in_WeightMax: 12,
 in_FingergripTypeTop: "NoFingergrip",
 in_FingergripTypeBtm: "NoFingergrip",
 in_HandleDesign: "50",
 in_HandlePosType: "StripeTop",
 Descriptor: "60mm_1_1_115mm",
 TableSequence: 582
}
,{
 _id: 1488,
 in_TypeElement: "All",
 in_FrontDesign: "WoodFrame",
 in_AdditionalInfo1: "All",
 in_AdditionalInfo2: "All",
 in_AdditionalInfo3: "WidthCoveredHeight",
 in_FrameWidthMin: 100,
 in_FrameWidthMax: 120,
 in_FrontHeightMin: 1500,
 in_FrontHeightMax: 2100,
 in_FrontWidthMin: 0,
 in_FrontWidthMax: 700,
 in_WeightMax: 17,
 in_FingergripTypeTop: "NoFingergrip",
 in_FingergripTypeBtm: "NoFingergrip",
 in_HandleDesign: "50",
 in_HandlePosType: "StripeTop",
 Descriptor: "60mm_1_1_1_115mm",
 TableSequence: 583
}
,{
 _id: 1489,
 in_TypeElement: "All",
 in_FrontDesign: "WoodFrame",
 in_AdditionalInfo1: "All",
 in_AdditionalInfo2: "All",
 in_AdditionalInfo3: "WidthCoveredHeight",
 in_FrameWidthMin: 100,
 in_FrameWidthMax: 120,
 in_FrontHeightMin: 2100,
 in_FrontHeightMax: 2500,
 in_FrontWidthMin: 0,
 in_FrontWidthMax: 700,
 in_WeightMax: 22,
 in_FingergripTypeTop: "NoFingergrip",
 in_FingergripTypeBtm: "NoFingergrip",
 in_HandleDesign: "50",
 in_HandlePosType: "StripeTop",
 Descriptor: "60mm_1_1_1_1_115mm",
 TableSequence: 584
}
,{
 _id: 1490,
 in_TypeElement: "All",
 in_FrontDesign: "WoodFrame",
 in_AdditionalInfo1: "All",
 in_AdditionalInfo2: "All",
 in_AdditionalInfo3: "WidthCoveredHeight",
 in_FrameWidthMin: 100,
 in_FrameWidthMax: 120,
 in_FrontHeightMin: 2500,
 in_FrontHeightMax: 3000,
 in_FrontWidthMin: 0,
 in_FrontWidthMax: 700,
 in_WeightMax: 28,
 in_FingergripTypeTop: "NoFingergrip",
 in_FingergripTypeBtm: "NoFingergrip",
 in_HandleDesign: "50",
 in_HandlePosType: "StripeTop",
 Descriptor: "60mm_1_1_1_1_1_115mm",
 TableSequence: 585
}
];
